In [1]:
from pycaret.classification import *
import numpy as np
import pandas as pd
import tensorflow as tf

column_names = ["duration", "protocol_type", "service", "flag", "src_bytes", "dst_bytes", "land",
                "wrong_fragment", "urgent", "hot", "num_failed_logins", "logged_in", "num_compromised",
                "root_shell", "su_attempted", "num_root", "num_file_creations", "num_shells", "num_access_files",
                "num_outbound_cmds", "is_host_login", "is_guest_login", "count", "srv_count", "serror_rate",
                "srv_serror_rate", "rerror_rate", "srv_rerror_rate", "same_srv_rate", "diff_srv_rate",
                "srv_diff_host_rate", "dst_host_count", "dst_host_srv_count", "dst_host_same_srv_rate",
                "dst_host_diff_srv_rate", "dst_host_same_src_port_rate", "dst_host_srv_diff_host_rate",
                "dst_host_serror_rate", "dst_host_srv_serror_rate", "dst_host_rerror_rate",
                "dst_host_srv_rerror_rate", "label", "difficulty_level"]
path = 'C:\\Users\\Jovana\\PycharmProjects\\neural_network_DNN\\include\\KDDTrain+.txt'
path2 = 'C:\\Users\\Jovana\\PycharmProjects\\neural_network_DNN\\include\\KDDTest+.txt'

ds_train = pd.read_csv(path, header=None, names=column_names)
ds_test = pd.read_csv(path2, header=None, names=column_names)
ds = pd.concat([ds_train, ds_test], axis=0)
ds.head()

duration protocol_type   service flag  src_bytes  dst_bytes  land  \
0         0           tcp  ftp_data   SF        491          0     0   
1         0           udp     other   SF        146          0     0   
2         0           tcp   private   S0          0          0     0   
3         0           tcp      http   SF        232       8153     0   
4         0           tcp      http   SF        199        420     0   

   wrong_fragment  urgent  hot  num_failed_logins  logged_in  num_compromised  \
0               0       0    0                  0          0                0   
1               0       0    0                  0          0                0   
2               0       0    0                  0          0                0   
3               0       0    0                  0          1                0   
4               0       0    0                  0          1                0   

   root_shell  su_attempted  num_root  num_file_creations  num_shells  \
0           0             0         0                   0           0   
1           0             0         0                   0           0   
2           0             0         0                   0           0   
3           0             0         0                   0           0   
4           0             0         0                   0           0   

   num_access_files  num_outbound_cmds  is_host_login  is_guest_login  count  \
0                 0                  0              0               0      2   
1                 0                  0              0               0     13   
2                 0                  0              0               0    123   
3                 0                  0              0               0      5   
4                 0                  0              0               0     30   

   srv_count  serror_rate  srv_serror_rate  rerror_rate  srv_rerror_rate  \
0          2          0.0              0.0          0.0              0.0   
1          1          0.0              0.0          0.0              0.0   
2          6          1.0              1.0          0.0              0.0   
3          5          0.2              0.2          0.0              0.0   
4         32          0.0              0.0          0.0              0.0   

   same_srv_rate  diff_srv_rate  srv_diff_host_rate  dst_host_count  \
0           1.00           0.00                0.00             150   
1           0.08           0.15                0.00             255   
2           0.05           0.07                0.00             255   
3           1.00           0.00                0.00              30   
4           1.00           0.00                0.09             255   

   dst_host_srv_count  dst_host_same_srv_rate  dst_host_diff_srv_rate  \
0                  25                    0.17                    0.03   
1                   1                    0.00                    0.60   
2                  26                    0.10                    0.05   
3                 255                    1.00                    0.00   
4                 255                    1.00                    0.00   

   dst_host_same_src_port_rate  dst_host_srv_diff_host_rate  \
0                         0.17                         0.00   
1                         0.88                         0.00   
2                         0.00                         0.00   
3                         0.03                         0.04   
4                         0.00                         0.00   

   dst_host_serror_rate  dst_host_srv_serror_rate  dst_host_rerror_rate  \
0                  0.00                      0.00                  0.05   
1                  0.00                      0.00                  0.00   
2                  1.00                      1.00                  0.00   
3                  0.03                      0.01                  0.00   
4                  0.00                      0.00                  0.00   

   dst_hos

In [2]:
ds.loc[(ds.label != 'normal'), 'label'] = 'attack'
ds = ds.drop('difficulty_level', axis=1)
ds

duration protocol_type   service flag  src_bytes  dst_bytes  land  \
0             0           tcp  ftp_data   SF        491          0     0   
1             0           udp     other   SF        146          0     0   
2             0           tcp   private   S0          0          0     0   
3             0           tcp      http   SF        232       8153     0   
4             0           tcp      http   SF        199        420     0   
...         ...           ...       ...  ...        ...        ...   ...   
22539         0           tcp      smtp   SF        794        333     0   
22540         0           tcp      http   SF        317        938     0   
22541         0           tcp      http   SF      54540       8314     0   
22542         0           udp  domain_u   SF         42         42     0   
22543         0           tcp    sunrpc  REJ          0          0     0   

       wrong_fragment  urgent  hot  num_failed_logins  logged_in  \
0                   0       0    0                  0          0   
1                   0       0    0                  0          0   
2                   0       0    0                  0          0   
3                   0       0    0                  0          1   
4                   0       0    0                  0          1   
...               ...     ...  ...                ...        ...   
22539               0       0    0                  0          1   
22540               0       0    0                  0          1   
22541               0       0    2                  0          1   
22542               0       0    0                  0          0   
22543               0       0    0                  0          0   

       num_compromised  root_shell  su_attempted  num_root  \
0                    0           0             0         0   
1                    0           0             0         0   
2                    0           0             0         0   
3                    0           0             0         0   
4                    0           0             0         0   
...                ...         ...           ...       ...   
22539                0           0             0         0   
22540                0           0             0         0   
22541                1           0             0         0   
22542                0           0             0         0   
22543                0           0             0         0   

       num_file_creations  num_shells  num_access_files  num_outbound_cmds  \
0                       0           0                 0                  0   
1                       0           0                 0                  0   
2                       0           0                 0                  0   
3                       0           0                 0                  0   
4                       0           0                 0                  0   
...                   ...         ...               ...                ...   
22539                   0           0                 0                  0   
22540                   0           0                 0                  0   
22541                   0           0                 0                  0   
22542                   0           0                 0                  0   
22543                   0           0                 0                  0   

       is_host_login  is_guest_login  count  srv_count  serror_rate  \
0                  0               0      2          2          0.0   
1                  0               0     13          1          0.0   
2                  0               0    123          6          1.0   
3                  0               0      5          5          0.2   
4                  0               0     30         32          0.0   
...              ...             ...    ...        ...          ...   
22539              0               0      1          1          0.0   
22540              0       

In [3]:
dsp_tr=setup(data = ds,
             target = 'label',train_size=0.8,
             numeric_imputation = 'mean',
             categorical_features = ['protocol_type','service','flag'],
             normalize=True,normalize_method='minmax',
             feature_selection=True,feature_selection_threshold=0.2,
             silent = True, fold_shuffle=True, fix_imbalance=True)

In [4]:
X_train=get_config('X_train')
Y_train = get_config('y_train')
Y_test = get_config('y_test')
X_test = get_config('X_test')

In [5]:
Y_train

121155    0
91224     1
13982     1
57594     0
26210     1
         ..
17426     0
53046     0
10486     1
81521     1
102867    0
Name: label, Length: 118813, dtype: int32

In [8]:
Y_train=Y_train.replace({0:1,1:0})

In [9]:
Y_train

121155    1
91224     0
13982     0
57594     1
26210     0
         ..
17426     1
53046     1
10486     0
81521     0
102867    1
Name: label, Length: 118813, dtype: int64

In [11]:
Y_test

34114     0
102251    1
60383     1
92282     1
106659    0
         ..
103491    1
102838    0
19354     1
10941     1
9642      1
Name: label, Length: 29704, dtype: int64

In [12]:
Y_test=Y_test.replace({0:1,1:0})

In [13]:
Y_test

34114     1
102251    0
60383     0
92282     0
106659    1
         ..
103491    0
102838    1
19354     0
10941     0
9642      0
Name: label, Length: 29704, dtype: int64

In [15]:
from tensorflow.python.keras.layers import Activation
from keras.optimizers import SGD
from keras.models import Sequential
from keras.layers import Dense
from keras.layers.advanced_activations import PReLU
from keras.layers import Dropout
from keras.callbacks import EarlyStopping
act2 = PReLU(alpha_initializer='zeros', weights=None)
model2 = Sequential()
# define the NN architecture and activation function

model2.add(Dense(496, input_dim=41, activation=Activation(act2)))
model2.add(Dropout(0.1))
model2.add(Dense(248, activation='relu'))
model2.add(Dropout(0.1))
model2.add(Dense(124, activation='relu'))
model2.add(Dropout(0.1))
model2.add(Dense(62, activation='relu'))
model2.add(Dropout(0.1))
model2.add(Dense(1))
model2.add(Activation('sigmoid'))

sgd =SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
model2.compile(loss='binary_crossentropy', optimizer=sgd, metrics= ['accuracy'])
es = EarlyStopping(monitor='val_accuracy', mode='max', min_delta=0.0001,patience=5) ## early stopping
model2.fit(X_train, Y_train, validation_data=(X_test, Y_test), epochs=100, batch_size=64, callbacks=[es])

Epoch 1/100
1857/1857 [==============================] - 6s 3ms/step - loss: 0.1136 - accuracy: 0.9584 - val_loss: 0.0769 - val_accuracy: 0.9705
Epoch 2/100
1857/1857 [==============================] - 7s 4ms/step - loss: 0.0731 - accuracy: 0.9731 - val_loss: 0.0667 - val_accuracy: 0.9745
Epoch 3/100
1857/1857 [==============================] - 6s 3ms/step - loss: 0.0661 - accuracy: 0.9750 - val_loss: 0.0929 - val_accuracy: 0.9731
Epoch 4/100
1857/1857 [==============================] - 6s 3ms/step - loss: 0.0614 - accuracy: 0.9768 - val_loss: 0.0582 - val_accuracy: 0.9787
Epoch 5/100
1857/1857 [==============================] - 6s 3ms/step - loss: 0.0579 - accuracy: 0.9778 - val_loss: 0.0557 - val_accuracy: 0.9792
Epoch 6/100
1857/1857 [==============================] - 6s 3ms/step - loss: 0.0552 - accuracy: 0.9787 - val_loss: 0.0512 - val_accuracy: 0.9805
Epoch 7/100
1857/1857 [==============================] - 6s 3ms/step - loss: 0.0529 - accuracy: 0.9795 - val_loss: 0.0516 - val_ac

In [16]:
#training accuracy
train_acc2 = model2.evaluate(X_train, Y_train, verbose=0)
print("%s: %.2f%%" % (model2.metrics_names[1], train_acc2[1]*100))

accuracy: 98.94%


In [17]:
#calculate the test accuracy using evaluate function
test_acc2 = model2.evaluate(X_test, Y_test, verbose=0)
print("%s: %.2f%%" % (model2.metrics_names[1], test_acc2[1] * 100))

accuracy: 98.78%


In [18]:
from sklearn.metrics import accuracy_score
# or find the prediction accuracy using predict_classes (same as test accuracy)
y_pred2 = model2.predict_classes(X_test)
pred_accuracy2 = accuracy_score(Y_test, y_pred2)
pred_accuracy2

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).


0.9878130891462429

In [19]:
from sklearn.metrics import precision_score, recall_score, f1_score, roc_auc_score
# Precision
precision = precision_score(Y_test, y_pred2)
print('Precision : %f'% precision)

Precision : 0.985040


In [20]:
# Recall
recall = recall_score(Y_test, y_pred2)
print('Recall: %f' % recall)

Recall: 0.989723


In [21]:
# f1-score
f1 = f1_score(Y_test, y_pred2)
print('F1 score: %f' % f1)

F1 score: 0.987376


In [22]:
#TPR=0.9897
#FPR=0.0140

roc = roc_auc_score(Y_test, y_pred2)
print('ROC_AUC Score: %f' % roc)

ROC_AUC Score: 0.987881


In [23]:
from sklearn.metrics import confusion_matrix

# confusion matrix
confusionmatrix = confusion_matrix(Y_test, y_pred2)
print(confusionmatrix)

[[15185   215]
 [  147 14157]]


In [24]:
tn, fp, fn, tp = confusionmatrix.ravel()
(tn, fp, fn, tp)
#FPR= 1.4%
#FNR= 1.03%

(15185, 215, 147, 14157)

In [62]:
#we have 147 false negatives, want to go lower
#next experiment is trying with the class weights
from sklearn.utils import compute_class_weight
weights=compute_class_weight('balanced',[0,1], Y_train)
weights


array([0.96354657, 1.03932014])

In [67]:
act3 = PReLU(alpha_initializer='zeros', weights=None)
model3 = Sequential()
# define the NN architecture and activation function
model3.add(Dense(496, input_dim=41, activation=Activation(act3)))
model3.add(Dropout(0.1))
model3.add(Dense(248, activation='relu'))
model3.add(Dropout(0.1))
model3.add(Dense(124, activation='relu'))
model3.add(Dropout(0.1))
model3.add(Dense(62, activation='relu'))
model3.add(Dropout(0.1))
model3.add(Dense(1))
model3.add(Activation('sigmoid'))

sgd =SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
model3.compile(loss='binary_crossentropy', optimizer=sgd, metrics= ['accuracy'])
es = EarlyStopping(monitor='val_accuracy', mode='max', min_delta=0.0001,patience=5) ## early stopping
model3.fit(X_train, Y_train, validation_data=(X_test, Y_test), epochs=100, batch_size=64, callbacks=[es], class_weight={0:1,1:2})

Epoch 1/100
1857/1857 [==============================] - 7s 4ms/step - loss: 0.1517 - accuracy: 0.9564 - val_loss: 0.0719 - val_accuracy: 0.9737
Epoch 2/100
1857/1857 [==============================] - 6s 3ms/step - loss: 0.1051 - accuracy: 0.9710 - val_loss: 0.0649 - val_accuracy: 0.9762
Epoch 3/100
1857/1857 [==============================] - 6s 3ms/step - loss: 0.0940 - accuracy: 0.9734 - val_loss: 0.0660 - val_accuracy: 0.9744
Epoch 4/100
1857/1857 [==============================] - 6s 3ms/step - loss: 0.0882 - accuracy: 0.9750 - val_loss: 0.0678 - val_accuracy: 0.9745
Epoch 5/100
1857/1857 [==============================] - 6s 3ms/step - loss: 0.0848 - accuracy: 0.9757 - val_loss: 0.0558 - val_accuracy: 0.9776
Epoch 6/100
1857/1857 [==============================] - 6s 3ms/step - loss: 0.0807 - accuracy: 0.9769 - val_loss: 0.0568 - val_accuracy: 0.9761
Epoch 7/100
1857/1857 [==============================] - 7s 4ms/step - loss: 0.0772 - accuracy: 0.9777 - val_loss: 0.0509 - val_ac

In [68]:
y_pred3 = model3.predict_classes(X_test)
#recall= 99.2%
#precision = 97.42%
#F1 score = 98.3%
#ROC = 98.38%
#FPR = 2.44%

In [69]:
confusionmatrix2 = confusion_matrix(Y_test, y_pred3)
print(confusionmatrix2)

[[15024   376]
 [  115 14189]]


In [70]:
tn2, fp2, fn2, tp2 = confusionmatrix2.ravel()
(tn2, fp2, fn2, tp2)
#FNR=0.8%

(15024, 376, 115, 14189)

In [71]:
#we decreased a bit, let's try for multiclass now with this method
ds_multi = pd.concat([ds_train, ds_test], axis=0)
ds_multi = ds_multi.drop('difficulty_level', axis=1)


def change_label(df):
    df.label.replace(
        ['apache2', 'back', 'land', 'neptune', 'mailbomb', 'pod', 'processtable', 'smurf', 'teardrop', 'udpstorm',
         'worm'], 'Dos', inplace=True)
    df.label.replace(['ftp_write', 'guess_passwd', 'httptunnel', 'imap', 'multihop', 'named', 'phf', 'sendmail',
                      'snmpgetattack', 'snmpguess', 'spy', 'warezclient', 'warezmaster', 'xlock', 'xsnoop'], 'R2L',
                     inplace=True)
    df.label.replace(['ipsweep', 'mscan', 'nmap', 'portsweep', 'saint', 'satan'], 'Probe', inplace=True)
    df.label.replace(['buffer_overflow', 'loadmodule', 'perl', 'ps', 'rootkit', 'sqlattack', 'xterm'], 'U2R',
                     inplace=True)


# calling change_label() function
change_label(ds_multi)

In [72]:
#first only with smote
dsp_tr_multi=setup(data = ds_multi,
             target = 'label',train_size=0.8,
             numeric_imputation = 'mean',
             categorical_features = ['protocol_type','service','flag'],
             normalize=True,normalize_method='minmax',
             feature_selection=True,feature_selection_threshold=0.2,
             silent = True, fold_shuffle=True,fix_imbalance=True)

In [73]:
X_train_multi=get_config('X_train')
X_test_multi = get_config('X_test')
Y_train_multi = get_config('y_train')
Y_test_multi = get_config('y_test')

In [75]:
#now model for multiclass

act3 = PReLU(alpha_initializer='zeros', weights=None)
model3 = Sequential()
# define the NN architecture and activation function

model3.add(Dense(496, input_dim=38, activation=Activation(act3)))
model3.add(Dropout(0.1))
model3.add(Dense(248, activation='relu'))
model3.add(Dropout(0.1))
model3.add(Dense(124, activation='relu'))
model3.add(Dropout(0.1))
model3.add(Dense(62, activation='relu'))
model3.add(Dropout(0.1))
model3.add(Dense(5))
model3.add(Activation('softmax'))

sgd =SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
model3.compile(loss='sparse_categorical_crossentropy', optimizer=sgd, metrics= ['accuracy'])
es = EarlyStopping(monitor='val_accuracy', mode='max', min_delta=0.0001,patience=5) ## early stopping
model3.fit(X_train_multi, Y_train_multi, validation_data=(X_test_multi, Y_test_multi), epochs=100, batch_size=64, callbacks=[es])

Epoch 1/100
1857/1857 [==============================] - 6s 3ms/step - loss: 0.1660 - accuracy: 0.9488 - val_loss: 0.0937 - val_accuracy: 0.9691
Epoch 2/100
1857/1857 [==============================] - 6s 3ms/step - loss: 0.0944 - accuracy: 0.9684 - val_loss: 0.0878 - val_accuracy: 0.9719
Epoch 3/100
1857/1857 [==============================] - 6s 3ms/step - loss: 0.0833 - accuracy: 0.9717 - val_loss: 0.0837 - val_accuracy: 0.9747
Epoch 4/100
1857/1857 [==============================] - 6s 3ms/step - loss: 0.0767 - accuracy: 0.9737 - val_loss: 0.0809 - val_accuracy: 0.9750
Epoch 5/100
1857/1857 [==============================] - 6s 3ms/step - loss: 0.0728 - accuracy: 0.9745 - val_loss: 0.0682 - val_accuracy: 0.9769
Epoch 6/100
1857/1857 [==============================] - 6s 3ms/step - loss: 0.0690 - accuracy: 0.9754 - val_loss: 0.0618 - val_accuracy: 0.9789
Epoch 7/100
1857/1857 [==============================] - 6s 3ms/step - loss: 0.0655 - accuracy: 0.9766 - val_loss: 0.0577 - val_ac

In [76]:
#training accuracy
train_acc4 = model3.evaluate(X_train_multi, Y_train_multi, verbose=0)
print("%s: %.2f%%" % (model3.metrics_names[1], train_acc4[1]*100))

accuracy: 98.33%


In [77]:
#calculate the test accuracy using evaluate function
test_acc4 = model3.evaluate(X_test_multi, Y_test_multi, verbose=0)
print("%s: %.2f%%" % (model3.metrics_names[1], test_acc4[1] * 100))

accuracy: 98.21%


In [78]:
y_pred4 = model3.predict_classes(X_test_multi)
pred_accuracy4 = accuracy_score(Y_test_multi, y_pred4)
pred_accuracy4

0.9820899542149205

In [79]:
# Precision
precision4 = precision_score(Y_test_multi, y_pred4, average='micro')
print('Precision : %f'% precision4)

Precision : 0.982090


In [80]:
# confusion matrix
confusionmatrix4 = confusion_matrix(Y_test_multi, y_pred4)
print(confusionmatrix4)

[[10621     8     2     0    30]
 [    2  2809     4     0    28]
 [    0     2   678     0   122]
 [    0     0     4     5    15]
 [   44    68   202     1 15059]]


In [81]:
from sklearn.metrics import classification_report
target_names=['DoS','Probe','R2L','U2R','Normal']
print(classification_report(Y_test_multi, y_pred4, target_names=target_names))

              precision    recall  f1-score   support

         DoS       1.00      1.00      1.00     10661
       Probe       0.97      0.99      0.98      2843
         R2L       0.76      0.85      0.80       802
         U2R       0.83      0.21      0.33        24
      Normal       0.99      0.98      0.98     15374

    accuracy                           0.98     29704
   macro avg       0.91      0.80      0.82     29704
weighted avg       0.98      0.98      0.98     29704



In [82]:
#now this AND class weights
weights_multi=compute_class_weight('balanced',[0,1,2,3,4], Y_train_multi)
weights_multi

array([  0.55616252,   2.11523945,   7.72014295, 250.13263158,
         0.38525616])

In [87]:
act5 = PReLU(alpha_initializer='zeros', weights=None)
model5 = Sequential()
# define the NN architecture and activation function

model5.add(Dense(496, input_dim=38, activation=Activation(act3)))
model5.add(Dropout(0.1))
model5.add(Dense(248, activation='relu'))
model5.add(Dropout(0.1))
model5.add(Dense(124, activation='relu'))
model5.add(Dropout(0.1))
model5.add(Dense(62, activation='relu'))
model5.add(Dropout(0.1))
model5.add(Dense(5))
model5.add(Activation('softmax'))

sgd =SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
model5.compile(loss='sparse_categorical_crossentropy', optimizer=sgd, metrics= ['accuracy'])
es = EarlyStopping(monitor='val_accuracy', mode='max', min_delta=0.0001,patience=5) ## early stopping
model5.fit(X_train_multi, Y_train_multi, validation_data=(X_test_multi, Y_test_multi), epochs=100, batch_size=64, callbacks=[es], class_weight={0:0.556163,1:2.115239,2:7.720143,3:25.132632,4:0.385256})

Epoch 1/100
1857/1857 [==============================] - 7s 4ms/step - loss: 0.2504 - accuracy: 0.8891 - val_loss: 0.2170 - val_accuracy: 0.9115
Epoch 2/100
1857/1857 [==============================] - 6s 3ms/step - loss: 0.1646 - accuracy: 0.9265 - val_loss: 0.1559 - val_accuracy: 0.9430
Epoch 3/100
1857/1857 [==============================] - 6s 3ms/step - loss: 0.1485 - accuracy: 0.9331 - val_loss: 0.2173 - val_accuracy: 0.9252
Epoch 4/100
1857/1857 [==============================] - 6s 3ms/step - loss: 0.1382 - accuracy: 0.9375 - val_loss: 0.1850 - val_accuracy: 0.9220
Epoch 5/100
1857/1857 [==============================] - 7s 4ms/step - loss: 0.1303 - accuracy: 0.9385 - val_loss: 0.1226 - val_accuracy: 0.9550
Epoch 6/100
1857/1857 [==============================] - 6s 3ms/step - loss: 0.1266 - accuracy: 0.9411 - val_loss: 0.1275 - val_accuracy: 0.9499
Epoch 7/100
1857/1857 [==============================] - 6s 3ms/step - loss: 0.1249 - accuracy: 0.9411 - val_loss: 0.1059 - val_ac

In [88]:
y_pred5 = model5.predict_classes(X_test_multi)

In [89]:
# confusion matrix
confusionmatrix5 = confusion_matrix(Y_test_multi, y_pred5)
print(confusionmatrix5)

[[10538    14    19     0    90]
 [    3  2830     6     0     4]
 [    1     4   766     2    29]
 [    0     0    14     9     1]
 [  124   167  1054    17 14012]]


In [90]:
print(classification_report(Y_test_multi, y_pred5, target_names=target_names))

              precision    recall  f1-score   support

         DoS       0.99      0.99      0.99     10661
       Probe       0.94      1.00      0.97      2843
         R2L       0.41      0.96      0.58       802
         U2R       0.32      0.38      0.35        24
      Normal       0.99      0.91      0.95     15374

    accuracy                           0.95     29704
   macro avg       0.73      0.85      0.77     29704
weighted avg       0.97      0.95      0.95     29704

