In [1]:
from pycaret.classification import *
import numpy as np
import pandas as pd
import tensorflow as tf

column_names = ["duration", "protocol_type", "service", "flag", "src_bytes", "dst_bytes", "land",
                "wrong_fragment", "urgent", "hot", "num_failed_logins", "logged_in", "num_compromised",
                "root_shell", "su_attempted", "num_root", "num_file_creations", "num_shells", "num_access_files",
                "num_outbound_cmds", "is_host_login", "is_guest_login", "count", "srv_count", "serror_rate",
                "srv_serror_rate", "rerror_rate", "srv_rerror_rate", "same_srv_rate", "diff_srv_rate",
                "srv_diff_host_rate", "dst_host_count", "dst_host_srv_count", "dst_host_same_srv_rate",
                "dst_host_diff_srv_rate", "dst_host_same_src_port_rate", "dst_host_srv_diff_host_rate",
                "dst_host_serror_rate", "dst_host_srv_serror_rate", "dst_host_rerror_rate",
                "dst_host_srv_rerror_rate", "label", "difficulty_level"]
path = 'C:\\Users\\Jovana\\PycharmProjects\\neural_network_DNN\\include\\KDDTrain+.txt'
path2= 'C:\\Users\\Jovana\\PycharmProjects\\neural_network_DNN\\include\\KDDTest+.txt'

ds_train=pd.read_csv(path,header=None, names = column_names)
ds_test=pd.read_csv(path2, header=None, names = column_names)

In [2]:
ds=pd.concat([ds_train,ds_test], axis=0)

In [3]:
ds.head()

duration protocol_type   service flag  src_bytes  dst_bytes  land  \
0         0           tcp  ftp_data   SF        491          0     0   
1         0           udp     other   SF        146          0     0   
2         0           tcp   private   S0          0          0     0   
3         0           tcp      http   SF        232       8153     0   
4         0           tcp      http   SF        199        420     0   

   wrong_fragment  urgent  hot  num_failed_logins  logged_in  num_compromised  \
0               0       0    0                  0          0                0   
1               0       0    0                  0          0                0   
2               0       0    0                  0          0                0   
3               0       0    0                  0          1                0   
4               0       0    0                  0          1                0   

   root_shell  su_attempted  num_root  num_file_creations  num_shells  \
0           0             0         0                   0           0   
1           0             0         0                   0           0   
2           0             0         0                   0           0   
3           0             0         0                   0           0   
4           0             0         0                   0           0   

   num_access_files  num_outbound_cmds  is_host_login  is_guest_login  count  \
0                 0                  0              0               0      2   
1                 0                  0              0               0     13   
2                 0                  0              0               0    123   
3                 0                  0              0               0      5   
4                 0                  0              0               0     30   

   srv_count  serror_rate  srv_serror_rate  rerror_rate  srv_rerror_rate  \
0          2          0.0              0.0          0.0              0.0   
1          1          0.0              0.0          0.0              0.0   
2          6          1.0              1.0          0.0              0.0   
3          5          0.2              0.2          0.0              0.0   
4         32          0.0              0.0          0.0              0.0   

   same_srv_rate  diff_srv_rate  srv_diff_host_rate  dst_host_count  \
0           1.00           0.00                0.00             150   
1           0.08           0.15                0.00             255   
2           0.05           0.07                0.00             255   
3           1.00           0.00                0.00              30   
4           1.00           0.00                0.09             255   

   dst_host_srv_count  dst_host_same_srv_rate  dst_host_diff_srv_rate  \
0                  25                    0.17                    0.03   
1                   1                    0.00                    0.60   
2                  26                    0.10                    0.05   
3                 255                    1.00                    0.00   
4                 255                    1.00                    0.00   

   dst_host_same_src_port_rate  dst_host_srv_diff_host_rate  \
0                         0.17                         0.00   
1                         0.88                         0.00   
2                         0.00                         0.00   
3                         0.03                         0.04   
4                         0.00                         0.00   

   dst_host_serror_rate  dst_host_srv_serror_rate  dst_host_rerror_rate  \
0                  0.00                      0.00                  0.05   
1                  0.00                      0.00                  0.00   
2                  1.00                      1.00                  0.00   
3                  0.03                      0.01                  0.00   
4                  0.00                      0.00                  0.00   

   dst_hos

In [4]:
ds.loc[(ds.label != 'normal'),'label']='attack'

In [5]:
ds=ds.drop('difficulty_level',axis=1)

In [6]:
ds

duration protocol_type   service flag  src_bytes  dst_bytes  land  \
0             0           tcp  ftp_data   SF        491          0     0   
1             0           udp     other   SF        146          0     0   
2             0           tcp   private   S0          0          0     0   
3             0           tcp      http   SF        232       8153     0   
4             0           tcp      http   SF        199        420     0   
...         ...           ...       ...  ...        ...        ...   ...   
22539         0           tcp      smtp   SF        794        333     0   
22540         0           tcp      http   SF        317        938     0   
22541         0           tcp      http   SF      54540       8314     0   
22542         0           udp  domain_u   SF         42         42     0   
22543         0           tcp    sunrpc  REJ          0          0     0   

       wrong_fragment  urgent  hot  num_failed_logins  logged_in  \
0                   0       0    0                  0          0   
1                   0       0    0                  0          0   
2                   0       0    0                  0          0   
3                   0       0    0                  0          1   
4                   0       0    0                  0          1   
...               ...     ...  ...                ...        ...   
22539               0       0    0                  0          1   
22540               0       0    0                  0          1   
22541               0       0    2                  0          1   
22542               0       0    0                  0          0   
22543               0       0    0                  0          0   

       num_compromised  root_shell  su_attempted  num_root  \
0                    0           0             0         0   
1                    0           0             0         0   
2                    0           0             0         0   
3                    0           0             0         0   
4                    0           0             0         0   
...                ...         ...           ...       ...   
22539                0           0             0         0   
22540                0           0             0         0   
22541                1           0             0         0   
22542                0           0             0         0   
22543                0           0             0         0   

       num_file_creations  num_shells  num_access_files  num_outbound_cmds  \
0                       0           0                 0                  0   
1                       0           0                 0                  0   
2                       0           0                 0                  0   
3                       0           0                 0                  0   
4                       0           0                 0                  0   
...                   ...         ...               ...                ...   
22539                   0           0                 0                  0   
22540                   0           0                 0                  0   
22541                   0           0                 0                  0   
22542                   0           0                 0                  0   
22543                   0           0                 0                  0   

       is_host_login  is_guest_login  count  srv_count  serror_rate  \
0                  0               0      2          2          0.0   
1                  0               0     13          1          0.0   
2                  0               0    123          6          1.0   
3                  0               0      5          5          0.2   
4                  0               0     30         32          0.0   
...              ...             ...    ...        ...          ...   
22539              0               0      1          1          0.0   
22540              0       

In [8]:
dsp_tr=setup(data = ds,
             target = 'label',train_size=0.8,
             numeric_imputation = 'mean',
             categorical_features = ['protocol_type','service','flag'],
             normalize=True,normalize_method='minmax',
             feature_selection=True,feature_selection_threshold=0.2,
             silent = True, fold_shuffle=True)

In [19]:
import sklearn
sklearn.__version__

'0.23.2'

In [23]:
X_train=get_config('X_train')

In [24]:
X_train

count  srv_serror_rate  service_smtp  logged_in_1     src_bytes  \
55017   0.440313              1.0           0.0          0.0  0.000000e+00   
22397   0.001957              0.0           0.0          0.0  6.304513e-08   
7837    0.557730              0.0           0.0          0.0  0.000000e+00   
63593   0.001957              0.0           0.0          0.0  5.420432e-07   
58717   0.142857              0.0           0.0          0.0  3.260955e-08   
...          ...              ...           ...          ...           ...   
120779  0.583170              0.0           0.0          0.0  3.333420e-08   
8869    0.003914              0.0           0.0          1.0  1.681203e-07   
75861   0.001957              0.0           0.0          0.0  0.000000e+00   
109183  0.563601              1.0           0.0          0.0  0.000000e+00   
96709   0.563601              0.0           0.0          0.0  0.000000e+00   

        service_ecr_i  service_ftp_data  service_private  \
55017             0.0               0.0              0.0   
22397             0.0               0.0              0.0   
7837              0.0               0.0              1.0   
63593             0.0               1.0              0.0   
58717             0.0               0.0              0.0   
...               ...               ...              ...   
120779            0.0               0.0              0.0   
8869              0.0               0.0              0.0   
75861             0.0               0.0              1.0   
109183            0.0               0.0              1.0   
96709             0.0               0.0              1.0   

        dst_host_same_src_port_rate  protocol_type_udp  ...  duration  \
55017                          0.00                0.0  ...  0.000000   
22397                          0.00                0.0  ...  0.001116   
7837                           0.00                0.0  ...  0.000000   
63593                          0.02                0.0  ...  0.000000   
58717                          0.00                1.0  ...  0.000000   
...                             ...                ...  ...       ...   
120779                         0.00                1.0  ...  0.000000   
8869                           0.03                0.0  ...  0.000000   
75861                          0.04                0.0  ...  0.000000   
109183                         0.00                0.0  ...  0.000000   
96709                          0.00                0.0  ...  0.000000   

        same_srv_rate  flag_REJ  srv_diff_host_rate  srv_count  rerror_rate  \
55017            0.09       0.0                0.00   0.041096         0.00   
22397            1.00       0.0                0.00   0.001957         0.00   
7837             0.00       1.0                0.00   0.001957         0.84   
63593            1.00       0.0                0.00   0.001957         0.00   
58717            1.00       0.0                0.01   0.301370         0.00   
...               ...       ...                 ...        ...          ...   
120779           1.00       0.0                0.00   0.583170         0.00   
8869             1.00       0.0                0.67   0.005871         0.00   
75861            1.00       0.0                0.00   0.001957         1.00   
109183           0.05       0.0                0.00   0.025440         0.00   
96709            0.00       1.0                0.00   0.001957         0.88   

        flag_SF  serror_rate  protocol_type_tcp  dst_host_srv_rerror_rate  
55017       0.0         1.00                1.0                       0.0  
22397       1.0         0.00                1.0                       0.0  
7837        0.0         0.15                1.0                       1.0  
63593       1.0         0.00                1.0                       0.0  
58717       1.0         0.00                0.0                       0.0  
...         ...          ...                ...                       .

In [26]:
Y_train=get_config('y_train')

In [27]:
Y_test=get_config('y_test')

In [28]:
X_test=get_config('X_test')

In [30]:
#now we make and test the neural networks
from tensorflow.python.keras.layers import Activation
from keras.optimizers import SGD
from keras.models import Sequential
from keras.layers import Dense
from keras.layers.advanced_activations import PReLU
from keras.layers import Dropout
from keras.callbacks import EarlyStopping
act2 = PReLU(alpha_initializer='zeros', weights=None)
model2 = Sequential()
# define the NN architecture and activation function

model2.add(Dense(496, input_dim=41, activation=Activation(act2)))
model2.add(Dropout(0.1))
model2.add(Dense(248, activation='relu'))
model2.add(Dropout(0.1))
model2.add(Dense(124, activation='relu'))
model2.add(Dropout(0.1))
model2.add(Dense(62, activation='relu'))
model2.add(Dropout(0.1))
model2.add(Dense(1))
model2.add(Activation('sigmoid'))

sgd =SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
model2.compile(loss='binary_crossentropy', optimizer=sgd, metrics= ['accuracy'])
es = EarlyStopping(monitor='val_accuracy', mode='max', min_delta=0.0001,patience=5) ## early stopping
model2.fit(X_train, Y_train, validation_data=(X_test, Y_test), epochs=100, batch_size=64, callbacks=[es])

Epoch 1/100
1857/1857 [==============================] - 6s 3ms/step - loss: 0.1105 - accuracy: 0.9605 - val_loss: 0.0753 - val_accuracy: 0.9715
Epoch 2/100
1857/1857 [==============================] - 6s 3ms/step - loss: 0.0730 - accuracy: 0.9734 - val_loss: 0.0690 - val_accuracy: 0.9752
Epoch 3/100
1857/1857 [==============================] - 6s 3ms/step - loss: 0.0669 - accuracy: 0.9750 - val_loss: 0.0670 - val_accuracy: 0.9734
Epoch 4/100
1857/1857 [==============================] - 6s 3ms/step - loss: 0.0624 - accuracy: 0.9767 - val_loss: 0.0565 - val_accuracy: 0.9793
Epoch 5/100
1857/1857 [==============================] - 6s 3ms/step - loss: 0.0595 - accuracy: 0.9775 - val_loss: 0.0633 - val_accuracy: 0.9766
Epoch 6/100
1857/1857 [==============================] - 6s 3ms/step - loss: 0.0566 - accuracy: 0.9787 - val_loss: 0.0534 - val_accuracy: 0.9794
Epoch 7/100
1857/1857 [==============================] - 6s 3ms/step - loss: 0.0546 - accuracy: 0.9792 - val_loss: 0.0521 - val_ac

In [32]:
#training accuracy
train_acc2 = model2.evaluate(X_train, Y_train, verbose=0)
print("%s: %.2f%%" % (model2.metrics_names[1], train_acc2[1]*100))

accuracy: 98.44%


In [33]:
#calculate the test accuracy using evaluate function
test_acc2 = model2.evaluate(X_test, Y_test, verbose=0)
print("%s: %.2f%%" % (model2.metrics_names[1], test_acc2[1] * 100))

accuracy: 98.27%


In [34]:
from sklearn.metrics import accuracy_score
# or find the prediction accuracy using predict_classes (same as test accuracy)
y_pred2 = model2.predict_classes(X_test)
pred_accuracy2 = accuracy_score(Y_test, y_pred2)
pred_accuracy2

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).


0.9826959332076488

In [35]:
from sklearn.metrics import precision_score, recall_score, f1_score, roc_auc_score
# Precision
precision = precision_score(Y_test, y_pred2)
print('Precision : %f'% precision)

Precision : 0.984476


In [36]:
# Recall
recall = recall_score(Y_test, y_pred2)
print('Recall: %f' % recall)

Recall: 0.982042


In [37]:
# f1-score
f1 = f1_score(Y_test, y_pred2)
print('F1 score: %f' % f1)

F1 score: 0.983257


In [38]:
roc = roc_auc_score(Y_test, y_pred2)
print('ROC_AUC Score: %f' % roc)

ROC_AUC Score: 0.982720


In [40]:
from sklearn.metrics import confusion_matrix

# confusion matrix
confusionmatrix = confusion_matrix(Y_test, y_pred2)
print(confusionmatrix)

[[14097   238]
 [  276 15093]]


In [41]:
model2.save("pycaret_model_NSLKDD_binary.h5")

In [43]:
list(X_train)

['count',
 'srv_serror_rate',
 'service_smtp',
 'logged_in_1',
 'src_bytes',
 'service_ecr_i',
 'service_ftp_data',
 'service_private',
 'dst_host_same_src_port_rate',
 'protocol_type_udp',
 'service_http',
 'dst_host_count',
 'flag_RSTR',
 'dst_host_srv_count',
 'service_pop_3',
 'dst_host_serror_rate',
 'hot',
 'dst_host_same_srv_rate',
 'dst_host_srv_diff_host_rate',
 'flag_S0',
 'service_finger',
 'protocol_type_icmp',
 'service_domain_u',
 'srv_rerror_rate',
 'dst_host_diff_srv_rate',
 'dst_host_srv_serror_rate',
 'service_eco_i',
 'dst_bytes',
 'dst_host_rerror_rate',
 'num_failed_logins_1',
 'diff_srv_rate',
 'duration',
 'same_srv_rate',
 'flag_REJ',
 'srv_diff_host_rate',
 'srv_count',
 'rerror_rate',
 'flag_SF',
 'serror_rate',
 'protocol_type_tcp',
 'dst_host_srv_rerror_rate']

In [44]:
#now let's try multiclass
ds_multi=pd.concat([ds_train,ds_test], axis=0)

In [47]:
ds_multi=ds_multi.drop('difficulty_level',axis=1)

In [49]:
def change_label(df):
    df.label.replace(
        ['apache2', 'back', 'land', 'neptune', 'mailbomb', 'pod', 'processtable', 'smurf', 'teardrop', 'udpstorm',
         'worm'], 'Dos', inplace=True)
    df.label.replace(['ftp_write', 'guess_passwd', 'httptunnel', 'imap', 'multihop', 'named', 'phf', 'sendmail',
                      'snmpgetattack', 'snmpguess', 'spy', 'warezclient', 'warezmaster', 'xlock', 'xsnoop'], 'R2L',
                     inplace=True)
    df.label.replace(['ipsweep', 'mscan', 'nmap', 'portsweep', 'saint', 'satan'], 'Probe', inplace=True)
    df.label.replace(['buffer_overflow', 'loadmodule', 'perl', 'ps', 'rootkit', 'sqlattack', 'xterm'], 'U2R',
                     inplace=True)


# calling change_label() function
change_label(ds_multi)

In [52]:
dsp_tr_multi=setup(data = ds_multi,
             target = 'label',train_size=0.8,
             numeric_imputation = 'mean',
             categorical_features = ['protocol_type','service','flag'],
             normalize=True,normalize_method='minmax',
             feature_selection=True,feature_selection_threshold=0.2,
             silent = True, fold_shuffle=True)

In [53]:
X_train_multi=get_config('X_train')

In [54]:
X_train_multi

count  srv_serror_rate  service_other  logged_in_1     src_bytes  \
99659   0.009785              0.0            0.0          1.0  2.318901e-07   
48665   0.156556              0.0            0.0          0.0  3.116023e-08   
48077   0.491194              1.0            0.0          0.0  0.000000e+00   
2820    0.086106              0.0            0.0          0.0  3.260955e-08   
67316   0.536204              1.0            0.0          0.0  0.000000e+00   
...          ...              ...            ...          ...           ...   
55972   0.115460              0.0            0.0          0.0  3.188489e-08   
105601  0.033268              0.0            0.0          0.0  2.029038e-08   
125458  0.017613              0.0            0.0          1.0  1.681203e-07   
95612   1.000000              0.0            0.0          0.0  7.478456e-07   
113211  0.256360              1.0            0.0          0.0  0.000000e+00   

        service_ecr_i  service_ftp_data  service_private  \
99659             0.0               0.0              0.0   
48665             0.0               0.0              0.0   
48077             0.0               0.0              1.0   
2820              0.0               0.0              0.0   
67316             0.0               0.0              0.0   
...               ...               ...              ...   
55972             0.0               0.0              0.0   
105601            0.0               0.0              1.0   
125458            0.0               0.0              0.0   
95612             1.0               0.0              0.0   
113211            0.0               0.0              0.0   

        dst_host_same_src_port_rate  service_http  ...  duration  \
99659                          0.02           1.0  ...       0.0   
48665                          0.00           0.0  ...       0.0   
48077                          0.00           0.0  ...       0.0   
2820                           0.88           0.0  ...       0.0   
67316                          0.00           0.0  ...       0.0   
...                             ...           ...  ...       ...   
55972                          0.00           0.0  ...       0.0   
105601                         0.08           0.0  ...       0.0   
125458                         0.01           1.0  ...       0.0   
95612                          0.92           0.0  ...       0.0   
113211                         0.00           0.0  ...       0.0   

        same_srv_rate  srv_diff_host_rate  srv_count  rerror_rate  flag_SF  \
99659            1.00                0.29   0.013699          0.0      1.0   
48665            1.00                0.01   0.313112          0.0      1.0   
48077            0.04                0.00   0.017613          0.0      0.0   
2820             1.00                0.01   0.387476          0.0      1.0   
67316            0.08                0.00   0.045010          0.0      0.0   
...               ...                 ...        ...          ...      ...   
55972            1.00                0.01   0.272016          0.0      1.0   
105601           1.00                0.00   0.033268          0.0      1.0   
125458           1.00                0.12   0.050881          0.0      1.0   
95612            1.00                0.00   1.000000          0.0      1.0   
113211           0.16                0.00   0.041096          0.0      0.0   

        serror_rate  service_ftp  protocol_type_tcp  dst_host_srv_rerror_rate  
99659           0.0          0.0                1.0                       0.0  
48665           0.0          0.0                0.0                       0.0  
48077           1.0          0.0                1.0                       0.0  
2820            0.0          0.0                0.0                       0.0  
67316           1.0          0.0                1.0                       0.0  
...             ...          ...                ...                       ...  
55972           0.0        

In [55]:
X_test_multi=get_config('X_test')
Y_train_multi=get_config('y_train')

In [56]:
Y_test_multi=get_config('y_test')

In [57]:
Y_train_multi

99659     4
48665     4
48077     0
2820      4
67316     0
         ..
55972     4
105601    0
125458    4
95612     0
113211    0
Name: label, Length: 118813, dtype: int32

In [58]:
#now model for multiclass

act3 = PReLU(alpha_initializer='zeros', weights=None)
model3 = Sequential()
# define the NN architecture and activation function

model3.add(Dense(496, input_dim=39, activation=Activation(act3)))
model3.add(Dropout(0.1))
model3.add(Dense(248, activation='relu'))
model3.add(Dropout(0.1))
model3.add(Dense(124, activation='relu'))
model3.add(Dropout(0.1))
model3.add(Dense(62, activation='relu'))
model3.add(Dropout(0.1))
model3.add(Dense(5))
model3.add(Activation('softmax'))

sgd =SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
model3.compile(loss='sparse_categorical_crossentropy', optimizer=sgd, metrics= ['accuracy'])
es = EarlyStopping(monitor='val_accuracy', mode='max', min_delta=0.0001,patience=5) ## early stopping
model3.fit(X_train_multi, Y_train_multi, validation_data=(X_test_multi, Y_test_multi), epochs=100, batch_size=64, callbacks=[es])

Epoch 1/100
1857/1857 [==============================] - 17s 9ms/step - loss: 0.1674 - accuracy: 0.9483 - val_loss: 0.0851 - val_accuracy: 0.9711
Epoch 2/100
1857/1857 [==============================] - 21s 11ms/step - loss: 0.0922 - accuracy: 0.9691 - val_loss: 0.0831 - val_accuracy: 0.9693
Epoch 3/100
1857/1857 [==============================] - 20s 11ms/step - loss: 0.0813 - accuracy: 0.9721 - val_loss: 0.0679 - val_accuracy: 0.9768
Epoch 4/100
1857/1857 [==============================] - 19s 10ms/step - loss: 0.0748 - accuracy: 0.9746 - val_loss: 0.0688 - val_accuracy: 0.9735
Epoch 5/100
1857/1857 [==============================] - 22s 12ms/step - loss: 0.0711 - accuracy: 0.9754 - val_loss: 0.0581 - val_accuracy: 0.9794
Epoch 6/100
1857/1857 [==============================] - 21s 11ms/step - loss: 0.0672 - accuracy: 0.9763 - val_loss: 0.0607 - val_accuracy: 0.9774
Epoch 7/100
1857/1857 [==============================] - 22s 12ms/step - loss: 0.0633 - accuracy: 0.9776 - val_loss: 0.

In [59]:
#training accuracy
train_acc3 = model3.evaluate(X_train_multi, Y_train_multi, verbose=0)
print("%s: %.2f%%" % (model3.metrics_names[1], train_acc3[1]*100))

accuracy: 98.18%


In [60]:
#calculate the test accuracy using evaluate function
test_acc3 = model3.evaluate(X_test_multi, Y_test_multi, verbose=0)
print("%s: %.2f%%" % (model3.metrics_names[1], test_acc3[1] * 100))

accuracy: 98.15%


In [61]:
y_pred3 = model3.predict_classes(X_test_multi)
pred_accuracy3 = accuracy_score(Y_test_multi, y_pred3)
pred_accuracy3

0.9815176407217883

In [66]:
# Precision
precision3 = precision_score(Y_test_multi, y_pred3, average='micro')
print('Precision : %f'% precision3)

Precision : 0.981518


In [64]:
recall3 = recall_score(Y_test_multi, y_pred3,average='micro')
print('Recall: %f' % recall3)

Recall: 0.981518


In [67]:
# confusion matrix
confusionmatrix3 = confusion_matrix(Y_test_multi, y_pred3)
print(confusionmatrix3)

[[10470    33     0     0   139]
 [    0  2844     1     0    19]
 [    2     6   641     0   109]
 [    0     0     6     0    16]
 [   32    75   111     0 15200]]


In [69]:
# f1-score
f1_3 = f1_score(Y_test_multi, y_pred3, average='micro')
print('F1 score: %f' % f1_3)

F1 score: 0.981518


In [70]:
model3.save("pycaret_model_NSLKDD_multiclass.h5")

In [71]:
X_test_multi

count  srv_serror_rate  service_other  logged_in_1     src_bytes  \
11997   0.033268             0.00            0.0          0.0  9.877069e-07   
119444  0.146771             0.00            0.0          0.0  3.188489e-08   
42239   0.491194             1.00            0.0          0.0  0.000000e+00   
7064    0.477495             0.00            0.0          0.0  0.000000e+00   
28922   0.001957             0.00            0.0          0.0  5.797253e-09   
...          ...              ...            ...          ...           ...   
104493  0.001957             0.00            0.0          1.0  7.485703e-07   
96202   0.015656             0.00            0.0          1.0  1.775409e-07   
58170   0.029354             0.03            0.0          1.0  1.521779e-07   
77776   0.001957             0.00            0.0          0.0  1.304382e-08   
91293   1.000000             0.00            0.0          0.0  7.478456e-07   

        service_ecr_i  service_ftp_data  service_private  \
11997             0.0               1.0              0.0   
119444            0.0               0.0              0.0   
42239             0.0               1.0              0.0   
7064              0.0               0.0              0.0   
28922             0.0               0.0              0.0   
...               ...               ...              ...   
104493            0.0               0.0              0.0   
96202             0.0               0.0              0.0   
58170             0.0               0.0              0.0   
77776             0.0               0.0              0.0   
91293             1.0               0.0              0.0   

        dst_host_same_src_port_rate  service_http  ...  duration  \
11997                          0.34           0.0  ...       0.0   
119444                         0.00           0.0  ...       0.0   
42239                          0.00           0.0  ...       0.0   
7064                           0.00           0.0  ...       0.0   
28922                          1.00           0.0  ...       0.0   
...                             ...           ...  ...       ...   
104493                         0.09           0.0  ...       0.0   
96202                          0.00           1.0  ...       0.0   
58170                          0.07           1.0  ...       0.0   
77776                          1.00           0.0  ...       0.0   
91293                          0.76           0.0  ...       0.0   

        same_srv_rate  srv_diff_host_rate  srv_count  rerror_rate  flag_SF  \
11997            1.00                0.00   0.033268          0.0      1.0   
119444           1.00                0.01   0.303327          0.0      1.0   
42239            0.04                0.00   0.019569          0.0      0.0   
7064             0.02                0.00   0.007828          1.0      0.0   
28922            1.00                1.00   0.039139          0.0      1.0   
...               ...                 ...        ...          ...      ...   
104493           1.00                0.00   0.001957          0.0      1.0   
96202            1.00                0.00   0.015656          0.0      1.0   
58170            1.00                0.06   0.064579          0.0      1.0   
77776            1.00                0.00   0.001957          0.0      1.0   
91293            1.00                0.00   1.000000          0.0      1.0   

        serror_rate  service_ftp  protocol_type_tcp  dst_host_srv_rerror_rate  
11997          0.00          0.0                1.0                       0.0  
119444         0.00          0.0                0.0                       0.0  
42239          1.00          0.0                1.0                       0.0  
7064           0.00          1.0                1.0                       1.0  
28922          0.00          0.0                0.0                       0.0  
...             ...          ...                ...                       ...  
104493         0.00        

In [72]:
from sklearn.metrics import classification_report
target_names=['DoS','Probe','R2L','U2R','Normal']
print(classification_report(Y_test_multi, y_pred3, target_names=target_names))

              precision    recall  f1-score   support

         DoS       1.00      0.98      0.99     10642
       Probe       0.96      0.99      0.98      2864
         R2L       0.84      0.85      0.85       758
         U2R       0.00      0.00      0.00        22
      Normal       0.98      0.99      0.98     15418

    accuracy                           0.98     29704
   macro avg       0.76      0.76      0.76     29704
weighted avg       0.98      0.98      0.98     29704



In [79]:
#just trying something
from keras.metrics import FalseNegatives
act4 = PReLU(alpha_initializer='zeros', weights=None)
model4 = Sequential()
# define the NN architecture and activation function

model4.add(Dense(496, input_dim=41, activation=Activation(act2)))
model4.add(Dropout(0.1))
model4.add(Dense(248, activation='relu'))
model4.add(Dropout(0.1))
model4.add(Dense(124, activation='relu'))
model4.add(Dropout(0.1))
model4.add(Dense(62, activation='relu'))
model4.add(Dropout(0.1))
model4.add(Dense(1))
model4.add(Activation('sigmoid'))

sgd2 =SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
model4.compile(loss='binary_crossentropy', optimizer=sgd2, metrics= [FalseNegatives()])
es = EarlyStopping(monitor='false_negatives_5', mode='max', min_delta=0.0001,patience=5) ## early stopping
model4.fit(X_train, Y_train, validation_data=(X_test, Y_test), epochs=100, batch_size=64)

Epoch 1/100
1857/1857 [==============================] - 6s 3ms/step - loss: 0.1136 - false_negatives_5: 1700.0000 - val_loss: 0.0762 - val_false_negatives_5: 527.0000
Epoch 2/100
1857/1857 [==============================] - 7s 4ms/step - loss: 0.0734 - false_negatives_5: 1281.0000 - val_loss: 0.0669 - val_false_negatives_5: 248.0000
Epoch 3/100
1857/1857 [==============================] - 7s 4ms/step - loss: 0.0665 - false_negatives_5: 1158.0000 - val_loss: 0.0584 - val_false_negatives_5: 331.0000
Epoch 4/100
1857/1857 [==============================] - 6s 3ms/step - loss: 0.0625 - false_negatives_5: 1104.0000 - val_loss: 0.0618 - val_false_negatives_5: 160.0000
Epoch 5/100
1857/1857 [==============================] - 6s 3ms/step - loss: 0.0593 - false_negatives_5: 1032.0000 - val_loss: 0.0621 - val_false_negatives_5: 148.0000
Epoch 6/100
1857/1857 [==============================] - 6s 3ms/step - loss: 0.0567 - false_negatives_5: 983.0000 - val_loss: 0.0500 - val_false_negatives_5: 22

In [80]:
y_pred4 = model4.predict_classes(X_test)
confusionmatrix4 = confusion_matrix(Y_test, y_pred4)
print(confusionmatrix4)

[[14134   201]
 [  141 15228]]
