In [1]:
import math

from pycaret.classification import *
import numpy as np
import pandas as pd
import tensorflow as tf
ds_full=pd.read_csv("D:\\Master Thesis Datasets\\UNSW-NB15 Source-Files\\UNSW-NB15 - CSV Files\\FULL.csv")
ds_full

Unnamed: 0         srcip  sport           dstip dsport proto state  \
0                 0    59.166.0.0  33661   149.171.126.9   1024   udp   CON   
1                 1    59.166.0.6   1464   149.171.126.7     53   udp   CON   
2                 2    59.166.0.5   3593   149.171.126.5     53   udp   CON   
3                 3    59.166.0.3  49664   149.171.126.0     53   udp   CON   
4                 4    59.166.0.0  32119   149.171.126.9    111   udp   CON   
...             ...           ...    ...             ...    ...   ...   ...   
2540038      440038    59.166.0.5  33094   149.171.126.7  43433   tcp   FIN   
2540039      440039    59.166.0.7  20848   149.171.126.4     21   tcp   CON   
2540040      440040    59.166.0.3  21511   149.171.126.9     21   tcp   CON   
2540041      440041    59.166.0.9  35433   149.171.126.0     80   tcp   CON   
2540042      440042  175.45.176.0  17293  149.171.126.17    110   tcp   CON   

              dur  sbytes  dbytes  sttl  dttl  sloss  dloss   service  \
0        0.036133     528     304    31    29      0      0         -   
1        0.001119     146     178    31    29      0      0       dns   
2        0.001209     132     164    31    29      0      0       dns   
3        0.001169     146     178    31    29      0      0       dns   
4        0.078339     568     312    31    29      0      0         -   
...           ...     ...     ...   ...   ...    ...    ...       ...   
2540038  0.087306     320    1828    31    29      1      2  ftp-data   
2540039  0.365058     456     346    31    29      2      2       ftp   
2540040  6.335154    1802    2088    31    29      7      9       ftp   
2540041  2.200934    3498  166054    31    29      2     57      http   
2540042  0.942984     574     676    62   252      5      6      pop3   

                 Sload          Dload  Spkts  Dpkts  swin  dwin       stcpb  \
0         87676.085940   50480.171880      4      4     0     0           0   
1        521894.531300  636282.375000      2      2     0     0           0   
2        436724.562500  542597.187500      2      2     0     0           0   
3        499572.250000  609067.562500      2      2     0     0           0   
4         43503.234380   23896.142580      4      4     0     0           0   
...                ...            ...    ...    ...   ...   ...         ...   
2540038   24465.671880  146610.765600      6      8   255   255  4035116044   
2540039    8743.816406    6333.240234      8      6   255   255  1529727621   
2540040    2204.839844    2549.582764     32     30   255   255   497208793   
2540041   12496.513670  598375.062500     58    116   255   255  1289728069   
2540042    4470.913574    5259.898438     12     12   255   255  3026824982   

              dtcpb  smeansz  dmeansz  trans_depth  res_bdy_len          Sjit  \
0                 0      132       76            0            0      9.891010   
1                 0       73       89            0            0      0.000000   
2                 0       66       82            0            0      0.000000   
3                 0       73       89            0            0      0.000000   
4                 0      142       78            0            0     29.682221   
...             ...      ...      ...          ...          ...           ...   
2540038   222196311       53      229            0            0   1221.136547   
2540039   185369967       57       58            0            0   3961.093354   
2540040   889904111       56       70            0            0  13233.728560   
2540041  3436097151       60     1432            1        79745   2868.893137   
2540042  3748412468       48       56            0            0   3903.523582   

                Djit       Stime       Ltime     Sintpkt     Dintpkt  \
0          10.682733  1421927414  1421927414    7.005000    7.564333   
1           0.000000  1421927414  1421927414    0.017000    0.013000   
2           0.000000  1421927414  1421927414 

In [2]:
ds_full.drop(columns="Unnamed: 0",inplace=True)
ds_full

srcip  sport           dstip dsport proto state       dur  \
0          59.166.0.0  33661   149.171.126.9   1024   udp   CON  0.036133   
1          59.166.0.6   1464   149.171.126.7     53   udp   CON  0.001119   
2          59.166.0.5   3593   149.171.126.5     53   udp   CON  0.001209   
3          59.166.0.3  49664   149.171.126.0     53   udp   CON  0.001169   
4          59.166.0.0  32119   149.171.126.9    111   udp   CON  0.078339   
...               ...    ...             ...    ...   ...   ...       ...   
2540038    59.166.0.5  33094   149.171.126.7  43433   tcp   FIN  0.087306   
2540039    59.166.0.7  20848   149.171.126.4     21   tcp   CON  0.365058   
2540040    59.166.0.3  21511   149.171.126.9     21   tcp   CON  6.335154   
2540041    59.166.0.9  35433   149.171.126.0     80   tcp   CON  2.200934   
2540042  175.45.176.0  17293  149.171.126.17    110   tcp   CON  0.942984   

         sbytes  dbytes  sttl  dttl  sloss  dloss   service          Sload  \
0           528     304    31    29      0      0         -   87676.085940   
1           146     178    31    29      0      0       dns  521894.531300   
2           132     164    31    29      0      0       dns  436724.562500   
3           146     178    31    29      0      0       dns  499572.250000   
4           568     312    31    29      0      0         -   43503.234380   
...         ...     ...   ...   ...    ...    ...       ...            ...   
2540038     320    1828    31    29      1      2  ftp-data   24465.671880   
2540039     456     346    31    29      2      2       ftp    8743.816406   
2540040    1802    2088    31    29      7      9       ftp    2204.839844   
2540041    3498  166054    31    29      2     57      http   12496.513670   
2540042     574     676    62   252      5      6      pop3    4470.913574   

                 Dload  Spkts  Dpkts  swin  dwin       stcpb       dtcpb  \
0         50480.171880      4      4     0     0           0           0   
1        636282.375000      2      2     0     0           0           0   
2        542597.187500      2      2     0     0           0           0   
3        609067.562500      2      2     0     0           0           0   
4         23896.142580      4      4     0     0           0           0   
...                ...    ...    ...   ...   ...         ...         ...   
2540038  146610.765600      6      8   255   255  4035116044   222196311   
2540039    6333.240234      8      6   255   255  1529727621   185369967   
2540040    2549.582764     32     30   255   255   497208793   889904111   
2540041  598375.062500     58    116   255   255  1289728069  3436097151   
2540042    5259.898438     12     12   255   255  3026824982  3748412468   

         smeansz  dmeansz  trans_depth  res_bdy_len          Sjit  \
0            132       76            0            0      9.891010   
1             73       89            0            0      0.000000   
2             66       82            0            0      0.000000   
3             73       89            0            0      0.000000   
4            142       78            0            0     29.682221   
...          ...      ...          ...          ...           ...   
2540038       53      229            0            0   1221.136547   
2540039       57       58            0            0   3961.093354   
2540040       56       70            0            0  13233.728560   
2540041       60     1432            1        79745   2868.893137   
2540042       48       56            0            0   3903.523582   

                Djit       Stime       Ltime     Sintpkt     Dintpkt  \
0          10.682733  1421927414  1421927414    7.005000    7.564333   
1           0.000000  1421927414  1421927414    0.017000    0.013000   
2           0.000000  1421927414  1421927414    0.043000    0.014000   
3           0.000000  1421927414  1421927414    0.005000    0.003000   
4          34.370340  1421927414  1421927414   21.00

In [3]:
# see how many duplicates
ds_full.duplicated().sum()

480625

In [4]:
#remove these duplicates
ds_full_new=ds_full.drop_duplicates()
ds_full_new

srcip  sport           dstip dsport proto state       dur  \
0          59.166.0.0  33661   149.171.126.9   1024   udp   CON  0.036133   
1          59.166.0.6   1464   149.171.126.7     53   udp   CON  0.001119   
2          59.166.0.5   3593   149.171.126.5     53   udp   CON  0.001209   
3          59.166.0.3  49664   149.171.126.0     53   udp   CON  0.001169   
4          59.166.0.0  32119   149.171.126.9    111   udp   CON  0.078339   
...               ...    ...             ...    ...   ...   ...       ...   
2540035    59.166.0.1  38606   149.171.126.9     80   tcp   CON  0.564998   
2540037    59.166.0.1  38606   149.171.126.9     80   tcp   CON  0.564998   
2540038    59.166.0.5  33094   149.171.126.7  43433   tcp   FIN  0.087306   
2540041    59.166.0.9  35433   149.171.126.0     80   tcp   CON  2.200934   
2540042  175.45.176.0  17293  149.171.126.17    110   tcp   CON  0.942984   

         sbytes  dbytes  sttl  dttl  sloss  dloss   service          Sload  \
0           528     304    31    29      0      0         -   87676.085940   
1           146     178    31    29      0      0       dns  521894.531300   
2           132     164    31    29      0      0       dns  436724.562500   
3           146     178    31    29      0      0       dns  499572.250000   
4           568     312    31    29      0      0         -   43503.234380   
...         ...     ...   ...   ...    ...    ...       ...            ...   
2540035   14106  772406    31    29      2    262      http  198981.250000   
2540037   14106  772406    31    29      2    262         -  198981.250000   
2540038     320    1828    31    29      1      2  ftp-data   24465.671880   
2540041    3498  166054    31    29      2     57      http   12496.513670   
2540042     574     676    62   252      5      6      pop3    4470.913574   

                Dload  Spkts  Dpkts  swin  dwin       stcpb       dtcpb  \
0        5.048017e+04      4      4     0     0           0           0   
1        6.362824e+05      2      2     0     0           0           0   
2        5.425972e+05      2      2     0     0           0           0   
3        6.090676e+05      2      2     0     0           0           0   
4        2.389614e+04      4      4     0     0           0           0   
...               ...    ...    ...   ...   ...         ...         ...   
2540035  1.091598e+07    262    526   255   255   162243658   163257853   
2540037  1.091598e+07    262    526   255   255   162243658   163257853   
2540038  1.466108e+05      6      8   255   255  4035116044   222196311   
2540041  5.983751e+05     58    116   255   255  1289728069  3436097151   
2540042  5.259898e+03     12     12   255   255  3026824982  3748412468   

         smeansz  dmeansz  trans_depth  res_bdy_len         Sjit         Djit  \
0            132       76            0            0     9.891010    10.682733   
1             73       89            0            0     0.000000     0.000000   
2             66       82            0            0     0.000000     0.000000   
3             73       89            0            0     0.000000     0.000000   
4            142       78            0            0    29.682221    34.370340   
...          ...      ...          ...          ...          ...          ...   
2540035       54     1468            1       372266   116.321921    69.874077   
2540037       54     1468            1       372266   116.321921    69.874077   
2540038       53      229            0            0  1221.136547    30.096029   
2540041       60     1432            1        79745  2868.893137  1951.035944   
2540042       48       56            0            0  3903.523582    95.650531   

              Stime       Ltime    Sintpkt    Dintpkt    tcprtt    synack  \
0        1421927414  1421927414   7.005000   7.564333  0.000000  0.000000   
1        1421927414  1421927414   0.017000   0.013000  0.000000  0.000000   
2        1421927414  1421927414   0.043000   0.01

In [5]:
# replace "-" with "undefined"
ds_full_new['service'].replace('-', 'undefined', inplace=True)
ds_full_new

srcip  sport           dstip dsport proto state       dur  \
0          59.166.0.0  33661   149.171.126.9   1024   udp   CON  0.036133   
1          59.166.0.6   1464   149.171.126.7     53   udp   CON  0.001119   
2          59.166.0.5   3593   149.171.126.5     53   udp   CON  0.001209   
3          59.166.0.3  49664   149.171.126.0     53   udp   CON  0.001169   
4          59.166.0.0  32119   149.171.126.9    111   udp   CON  0.078339   
...               ...    ...             ...    ...   ...   ...       ...   
2540035    59.166.0.1  38606   149.171.126.9     80   tcp   CON  0.564998   
2540037    59.166.0.1  38606   149.171.126.9     80   tcp   CON  0.564998   
2540038    59.166.0.5  33094   149.171.126.7  43433   tcp   FIN  0.087306   
2540041    59.166.0.9  35433   149.171.126.0     80   tcp   CON  2.200934   
2540042  175.45.176.0  17293  149.171.126.17    110   tcp   CON  0.942984   

         sbytes  dbytes  sttl  dttl  sloss  dloss    service          Sload  \
0           528     304    31    29      0      0  undefined   87676.085940   
1           146     178    31    29      0      0        dns  521894.531300   
2           132     164    31    29      0      0        dns  436724.562500   
3           146     178    31    29      0      0        dns  499572.250000   
4           568     312    31    29      0      0  undefined   43503.234380   
...         ...     ...   ...   ...    ...    ...        ...            ...   
2540035   14106  772406    31    29      2    262       http  198981.250000   
2540037   14106  772406    31    29      2    262  undefined  198981.250000   
2540038     320    1828    31    29      1      2   ftp-data   24465.671880   
2540041    3498  166054    31    29      2     57       http   12496.513670   
2540042     574     676    62   252      5      6       pop3    4470.913574   

                Dload  Spkts  Dpkts  swin  dwin       stcpb       dtcpb  \
0        5.048017e+04      4      4     0     0           0           0   
1        6.362824e+05      2      2     0     0           0           0   
2        5.425972e+05      2      2     0     0           0           0   
3        6.090676e+05      2      2     0     0           0           0   
4        2.389614e+04      4      4     0     0           0           0   
...               ...    ...    ...   ...   ...         ...         ...   
2540035  1.091598e+07    262    526   255   255   162243658   163257853   
2540037  1.091598e+07    262    526   255   255   162243658   163257853   
2540038  1.466108e+05      6      8   255   255  4035116044   222196311   
2540041  5.983751e+05     58    116   255   255  1289728069  3436097151   
2540042  5.259898e+03     12     12   255   255  3026824982  3748412468   

         smeansz  dmeansz  trans_depth  res_bdy_len         Sjit         Djit  \
0            132       76            0            0     9.891010    10.682733   
1             73       89            0            0     0.000000     0.000000   
2             66       82            0            0     0.000000     0.000000   
3             73       89            0            0     0.000000     0.000000   
4            142       78            0            0    29.682221    34.370340   
...          ...      ...          ...          ...          ...          ...   
2540035       54     1468            1       372266   116.321921    69.874077   
2540037       54     1468            1       372266   116.321921    69.874077   
2540038       53      229            0            0  1221.136547    30.096029   
2540041       60     1432            1        79745  2868.893137  1951.035944   
2540042       48       56            0            0  3903.523582    95.650531   

              Stime       Ltime    Sintpkt    Dintpkt    tcprtt    synack  \
0        1421927414  1421927414   7.005000   7.564333  0.000000  0.000000   
1        1421927414  1421927414   0.017000   0.013000  0.000000  0.000000   
2        1421927414  1421927414   0.0

In [6]:
#change NaN to Normal
import math
ds_full_new['attack_cat'].replace(math.nan,'Normal',inplace=True)

In [7]:
#Ignore source IP, destination IP and attack category (for binary) features when training and testing the model.
# drop source IP and destination IP
ds_full_new.drop(columns=['srcip','dstip'],inplace=True)
ds_full_new

sport dsport proto state       dur  sbytes  dbytes  sttl  dttl  \
0        33661   1024   udp   CON  0.036133     528     304    31    29   
1         1464     53   udp   CON  0.001119     146     178    31    29   
2         3593     53   udp   CON  0.001209     132     164    31    29   
3        49664     53   udp   CON  0.001169     146     178    31    29   
4        32119    111   udp   CON  0.078339     568     312    31    29   
...        ...    ...   ...   ...       ...     ...     ...   ...   ...   
2540035  38606     80   tcp   CON  0.564998   14106  772406    31    29   
2540037  38606     80   tcp   CON  0.564998   14106  772406    31    29   
2540038  33094  43433   tcp   FIN  0.087306     320    1828    31    29   
2540041  35433     80   tcp   CON  2.200934    3498  166054    31    29   
2540042  17293    110   tcp   CON  0.942984     574     676    62   252   

         sloss  dloss    service          Sload         Dload  Spkts  Dpkts  \
0            0      0  undefined   87676.085940  5.048017e+04      4      4   
1            0      0        dns  521894.531300  6.362824e+05      2      2   
2            0      0        dns  436724.562500  5.425972e+05      2      2   
3            0      0        dns  499572.250000  6.090676e+05      2      2   
4            0      0  undefined   43503.234380  2.389614e+04      4      4   
...        ...    ...        ...            ...           ...    ...    ...   
2540035      2    262       http  198981.250000  1.091598e+07    262    526   
2540037      2    262  undefined  198981.250000  1.091598e+07    262    526   
2540038      1      2   ftp-data   24465.671880  1.466108e+05      6      8   
2540041      2     57       http   12496.513670  5.983751e+05     58    116   
2540042      5      6       pop3    4470.913574  5.259898e+03     12     12   

         swin  dwin       stcpb       dtcpb  smeansz  dmeansz  trans_depth  \
0           0     0           0           0      132       76            0   
1           0     0           0           0       73       89            0   
2           0     0           0           0       66       82            0   
3           0     0           0           0       73       89            0   
4           0     0           0           0      142       78            0   
...       ...   ...         ...         ...      ...      ...          ...   
2540035   255   255   162243658   163257853       54     1468            1   
2540037   255   255   162243658   163257853       54     1468            1   
2540038   255   255  4035116044   222196311       53      229            0   
2540041   255   255  1289728069  3436097151       60     1432            1   
2540042   255   255  3026824982  3748412468       48       56            0   

         res_bdy_len         Sjit         Djit       Stime       Ltime  \
0                  0     9.891010    10.682733  1421927414  1421927414   
1                  0     0.000000     0.000000  1421927414  1421927414   
2                  0     0.000000     0.000000  1421927414  1421927414   
3                  0     0.000000     0.000000  1421927414  1421927414   
4                  0    29.682221    34.370340  1421927414  1421927414   
...              ...          ...          ...         ...         ...   
2540035       372266   116.321921    69.874077  1424262068  1424262069   
2540037       372266   116.321921    69.874077  1424262068  1424262069   
2540038            0  1221.136547    30.096029  1424262068  1424262069   
2540041        79745  2868.893137  1951.035944  1424262067  1424262069   
2540042            0  3903.523582    95.650531  1424262068  1424262069   

           Sintpkt    Dintpkt    tcprtt    synack    ackdat  is_sm_ips_ports  \
0         7.005000   7.564333  0.000000  0.000000  0.000000                0   
1         0.017000   0.013000  0.000000  0.000000  0.000000                0   
2         0.043000   0.014000  0.000000  0.000000  0.000000                0   
3         0.0

In [8]:
#make the multiclass now
ds_full_multiclass=ds_full_new.drop(columns='label')
ds_full_multiclass

sport dsport proto state       dur  sbytes  dbytes  sttl  dttl  \
0        33661   1024   udp   CON  0.036133     528     304    31    29   
1         1464     53   udp   CON  0.001119     146     178    31    29   
2         3593     53   udp   CON  0.001209     132     164    31    29   
3        49664     53   udp   CON  0.001169     146     178    31    29   
4        32119    111   udp   CON  0.078339     568     312    31    29   
...        ...    ...   ...   ...       ...     ...     ...   ...   ...   
2540035  38606     80   tcp   CON  0.564998   14106  772406    31    29   
2540037  38606     80   tcp   CON  0.564998   14106  772406    31    29   
2540038  33094  43433   tcp   FIN  0.087306     320    1828    31    29   
2540041  35433     80   tcp   CON  2.200934    3498  166054    31    29   
2540042  17293    110   tcp   CON  0.942984     574     676    62   252   

         sloss  dloss    service          Sload         Dload  Spkts  Dpkts  \
0            0      0  undefined   87676.085940  5.048017e+04      4      4   
1            0      0        dns  521894.531300  6.362824e+05      2      2   
2            0      0        dns  436724.562500  5.425972e+05      2      2   
3            0      0        dns  499572.250000  6.090676e+05      2      2   
4            0      0  undefined   43503.234380  2.389614e+04      4      4   
...        ...    ...        ...            ...           ...    ...    ...   
2540035      2    262       http  198981.250000  1.091598e+07    262    526   
2540037      2    262  undefined  198981.250000  1.091598e+07    262    526   
2540038      1      2   ftp-data   24465.671880  1.466108e+05      6      8   
2540041      2     57       http   12496.513670  5.983751e+05     58    116   
2540042      5      6       pop3    4470.913574  5.259898e+03     12     12   

         swin  dwin       stcpb       dtcpb  smeansz  dmeansz  trans_depth  \
0           0     0           0           0      132       76            0   
1           0     0           0           0       73       89            0   
2           0     0           0           0       66       82            0   
3           0     0           0           0       73       89            0   
4           0     0           0           0      142       78            0   
...       ...   ...         ...         ...      ...      ...          ...   
2540035   255   255   162243658   163257853       54     1468            1   
2540037   255   255   162243658   163257853       54     1468            1   
2540038   255   255  4035116044   222196311       53      229            0   
2540041   255   255  1289728069  3436097151       60     1432            1   
2540042   255   255  3026824982  3748412468       48       56            0   

         res_bdy_len         Sjit         Djit       Stime       Ltime  \
0                  0     9.891010    10.682733  1421927414  1421927414   
1                  0     0.000000     0.000000  1421927414  1421927414   
2                  0     0.000000     0.000000  1421927414  1421927414   
3                  0     0.000000     0.000000  1421927414  1421927414   
4                  0    29.682221    34.370340  1421927414  1421927414   
...              ...          ...          ...         ...         ...   
2540035       372266   116.321921    69.874077  1424262068  1424262069   
2540037       372266   116.321921    69.874077  1424262068  1424262069   
2540038            0  1221.136547    30.096029  1424262068  1424262069   
2540041        79745  2868.893137  1951.035944  1424262067  1424262069   
2540042            0  3903.523582    95.650531  1424262068  1424262069   

           Sintpkt    Dintpkt    tcprtt    synack    ackdat  is_sm_ips_ports  \
0         7.005000   7.564333  0.000000  0.000000  0.000000                0   
1         0.017000   0.013000  0.000000  0.000000  0.000000                0   
2         0.043000   0.014000  0.000000  0.000000  0.000000                0   
3         0.0

In [9]:
pd.value_counts(ds_full_multiclass.attack_cat.values)

Normal              1959772
Exploits              27600
Generic               25378
 Fuzzers              17804
 Reconnaissance       11617
DoS                    5665
 Fuzzers               3991
Analysis               2185
Reconnaissance         1740
Backdoor               1684
 Shellcode             1288
Backdoors               300
Shellcode               223
Worms                   171
dtype: int64

In [10]:
#there are some typos, have to fix
ds_full_multiclass['attack_cat'] = ds_full_multiclass['attack_cat'].str.strip()
pd.value_counts(ds_full_multiclass.attack_cat.values)

Normal            1959772
Exploits            27600
Generic             25378
Fuzzers             21795
Reconnaissance      13357
DoS                  5665
Analysis             2185
Backdoor             1684
Shellcode            1511
Backdoors             300
Worms                 171
dtype: int64

In [11]:
ds_full_multiclass['attack_cat'].replace('Backdoors','Backdoor',inplace=True)
pd.value_counts(ds_full_multiclass.attack_cat.values)

Normal            1959772
Exploits            27600
Generic             25378
Fuzzers             21795
Reconnaissance      13357
DoS                  5665
Analysis             2185
Backdoor             1984
Shellcode            1511
Worms                 171
dtype: int64

In [12]:
pd.unique(ds_full_multiclass.attack_cat)

array(['Normal', 'Exploits', 'Reconnaissance', 'DoS', 'Generic',
       'Shellcode', 'Fuzzers', 'Worms', 'Backdoor', 'Analysis'],
      dtype=object)

In [13]:
#now we should remove whitespaces everywhere
ds_full_multiclass.isnull().sum()

sport                     0
dsport                    0
proto                     0
state                     0
dur                       0
sbytes                    0
dbytes                    0
sttl                      0
dttl                      0
sloss                     0
dloss                     0
service                   0
Sload                     0
Dload                     0
Spkts                     0
Dpkts                     0
swin                      0
dwin                      0
stcpb                     0
dtcpb                     0
smeansz                   0
dmeansz                   0
trans_depth               0
res_bdy_len               0
Sjit                      0
Djit                      0
Stime                     0
Ltime                     0
Sintpkt                   0
Dintpkt                   0
tcprtt                    0
synack                    0
ackdat                    0
is_sm_ips_ports           0
ct_state_ttl              0
ct_flw_http_mthd    

In [16]:
pd.unique(ds_full_multiclass.ct_flw_http_mthd)

array([ 0.,  1.,  2.,  4., 14.,  8.,  6., 12., 10.,  3.,  5., 36.,  9.,
       16., 25., 30.])

In [15]:
ds_full_multiclass['ct_flw_http_mthd'].replace(math.nan, float(0),inplace=True)

In [19]:
pd.unique(ds_full_multiclass.is_ftp_login)

array([0., 1., 2., 4.])

In [18]:
ds_full_multiclass['is_ftp_login'].replace(math.nan, float(0),inplace=True)

In [24]:
pd.unique(ds_full_multiclass.ct_ftp_cmd)

array(['0', 1, 6, 2, 4, 8, 5, 3, '1', '2', '4'], dtype=object)

In [23]:
ds_full_multiclass['ct_ftp_cmd'].replace(0, '0',inplace=True)

In [25]:
dsp_tr_multiclass_full=setup(data = ds_full_multiclass,
             target = 'attack_cat',train_size=0.8,
             numeric_imputation = 'mean',
             categorical_features = ['proto','service','state'],
             numeric_features=['dur','Spkts','Dpkts','sbytes','dbytes','sttl','dttl','Sload','Dload','sloss','dloss','Sintpkt','Dintpkt','Sjit','Djit','swin','stcpb','dtcpb','dwin','tcprtt','synack','ackdat','smeansz','dmeansz','trans_depth','res_bdy_len','ct_srv_src','ct_state_ttl','ct_dst_ltm','ct_src_dport_ltm','ct_dst_sport_ltm',
                               'ct_dst_src_ltm','is_ftp_login','ct_ftp_cmd','ct_flw_http_mthd','ct_src_ ltm','ct_srv_dst','is_sm_ips_ports'],
                ignore_features=['dsport','sport','Stime','Ltime'],
             normalize=True,normalize_method='minmax',
             feature_selection=True,feature_selection_threshold=0.2,
             silent = True, fold_shuffle=True)

In [26]:
X_train_mul_full=get_config('X_train')
X_test_mul_full = get_config('X_test')
Y_train_mul_full = get_config('y_train')
Y_test_mul_full = get_config('y_test')

In [27]:
from tensorflow.python.keras.layers import Activation
from keras.optimizers import SGD
from keras.models import Sequential
from keras.layers import Dense
from keras.layers.advanced_activations import PReLU
from keras.layers import Dropout
from keras.callbacks import EarlyStopping
act11 = PReLU(alpha_initializer='zeros', weights=None)
model11 = Sequential()
# define the NN architecture and activation function

model11.add(Dense(496, input_dim=42, activation=Activation(act11)))
model11.add(Dropout(0.1))
model11.add(Dense(248, activation='relu'))
model11.add(Dropout(0.1))
model11.add(Dense(124, activation='relu'))
model11.add(Dropout(0.1))
model11.add(Dense(62, activation='relu'))
model11.add(Dropout(0.1))
model11.add(Dense(10))
model11.add(Activation('softmax'))

sgd =SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
model11.compile(loss='sparse_categorical_crossentropy', optimizer=sgd, metrics= ['accuracy'])
es = EarlyStopping(monitor='val_accuracy', mode='max', min_delta=0.0001,patience=5) ## early stopping
model11.fit(X_train_mul_full, Y_train_mul_full, validation_data=(X_test_mul_full, Y_test_mul_full), epochs=100, batch_size=64, callbacks=[es])

Epoch 1/100
25743/25743 [==============================] - 85s 3ms/step - loss: 0.0766 - accuracy: 0.9710 - val_loss: 0.0679 - val_accuracy: 0.9721
Epoch 2/100
25743/25743 [==============================] - 82s 3ms/step - loss: 0.0649 - accuracy: 0.9739 - val_loss: 0.0621 - val_accuracy: 0.9750
Epoch 3/100
25743/25743 [==============================] - 83s 3ms/step - loss: 0.0628 - accuracy: 0.9745 - val_loss: 0.0619 - val_accuracy: 0.9744
Epoch 4/100
25743/25743 [==============================] - 80s 3ms/step - loss: 0.0615 - accuracy: 0.9750 - val_loss: 0.0592 - val_accuracy: 0.9759
Epoch 5/100
25743/25743 [==============================] - 81s 3ms/step - loss: 0.0606 - accuracy: 0.9752 - val_loss: 0.0587 - val_accuracy: 0.9759
Epoch 6/100
25743/25743 [==============================] - 81s 3ms/step - loss: 0.0597 - accuracy: 0.9756 - val_loss: 0.0594 - val_accuracy: 0.9761
Epoch 7/100
25743/25743 [==============================] - 79s 3ms/step - loss: 0.0591 - accuracy: 0.9759 - val_

In [28]:
from sklearn.metrics import confusion_matrix

# confusion matrix
y_pred11 = model11.predict_classes(X_test_mul_full)
confusionmatrix11 = confusion_matrix(Y_test_mul_full, y_pred11)
print(confusionmatrix11)

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
[[     3      0      4     14    320      0     75      8      0      0]
 [     0      3      5     19    308      3     19     50      0      0]
 [     0      3     53    455    379     59     74     77      9      0]
 [     0      1     21   4302    487     98    270    426     19      0]
 [     0      0      3     85   2006     30   1982    151     17      0]
 [     1      0      8    373    356   4275     41     45      4      0]
 [     0      0      5    239    877     32 390420    224     13      0]
 [     0      0      4     80    329      7    133   2220      0      0]
 [     0      0      0     30     16      4     43    146     86      0]
 [     0 

In [29]:
from sklearn.metrics import classification_report, multilabel_confusion_matrix
target_names=['Analysis','Backdoor','DoS','Exploits','Fuzzers','Generic','Normal','Recconnaissanse','Shellcode','Worms']
print(classification_report(Y_test_mul_full, y_pred11, target_names=target_names))

                 precision    recall  f1-score   support

       Analysis       0.75      0.01      0.01       424
       Backdoor       0.43      0.01      0.01       407
            DoS       0.51      0.05      0.09      1109
       Exploits       0.77      0.76      0.77      5624
        Fuzzers       0.39      0.47      0.43      4274
        Generic       0.95      0.84      0.89      5103
         Normal       0.99      1.00      0.99    391810
Recconnaissanse       0.66      0.80      0.73      2773
      Shellcode       0.57      0.26      0.36       325
          Worms       0.00      0.00      0.00        35

       accuracy                           0.98    411884
      macro avg       0.60      0.42      0.43    411884
   weighted avg       0.98      0.98      0.98    411884



In [32]:
from sklearn.metrics import multilabel_confusion_matrix
multilabel_matrix = multilabel_confusion_matrix(Y_test_mul_full, y_pred11)
print(multilabel_matrix)

[[[411459      1]
  [   421      3]]

 [[411473      4]
  [   404      3]]

 [[410725     50]
  [  1056     53]]

 [[404946   1314]
  [  1322   4302]]

 [[404533   3077]
  [  2268   2006]]

 [[406541    240]
  [   828   4275]]

 [[ 17435   2639]
  [  1390 390420]]

 [[407984   1127]
  [   553   2220]]

 [[411495     64]
  [   239     86]]

 [[411849      0]
  [    35      0]]]


In [34]:
from sklearn.utils import compute_class_weight
weights_multi=compute_class_weight('balanced',[0,1,2,3,4,5,6,7,8,9], Y_train_mul_full)
weights_multi

array([9.35567291e+01, 1.04472670e+02, 3.61618525e+01, 7.49696942e+00,
       9.40319616e+00, 8.12593835e+00, 1.05074868e-01, 1.55662698e+01,
       1.38915177e+02, 1.21142206e+03])

In [41]:
act12 = PReLU(alpha_initializer='zeros', weights=None)
model12 = Sequential()
# define the NN architecture and activation function

model12.add(Dense(496, input_dim=42, activation=Activation(act12)))
model12.add(Dropout(0.1))
model12.add(Dense(248, activation='relu'))
model12.add(Dropout(0.1))
model12.add(Dense(124, activation='relu'))
model12.add(Dropout(0.1))
model12.add(Dense(62, activation='relu'))
model12.add(Dropout(0.1))
model12.add(Dense(10))
model12.add(Activation('softmax'))

sgd =SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
model12.compile(loss='sparse_categorical_crossentropy', optimizer=sgd, metrics= ['accuracy'])
es = EarlyStopping(monitor='val_accuracy', mode='max', min_delta=0.0001,patience=5) ## early stopping
model12.fit(X_train_mul_full, Y_train_mul_full, validation_data=(X_test_mul_full, Y_test_mul_full), epochs=100, batch_size=64, callbacks=[es], class_weight={0:9,1:10,2:5,3:3,4:3.5,5:3,6:1,7:4,8:15,9:20})

Epoch 1/100
25743/25743 [==============================] - 81s 3ms/step - loss: 0.2623 - accuracy: 0.9681 - val_loss: 0.0717 - val_accuracy: 0.9704
Epoch 2/100
25743/25743 [==============================] - 85s 3ms/step - loss: 0.2378 - accuracy: 0.9697 - val_loss: 0.0709 - val_accuracy: 0.9705
Epoch 3/100
25743/25743 [==============================] - 86s 3ms/step - loss: 0.2305 - accuracy: 0.9704 - val_loss: 0.0694 - val_accuracy: 0.9716
Epoch 4/100
25743/25743 [==============================] - 82s 3ms/step - loss: 0.2252 - accuracy: 0.9708 - val_loss: 0.0658 - val_accuracy: 0.9717
Epoch 5/100
25743/25743 [==============================] - 81s 3ms/step - loss: 0.2220 - accuracy: 0.9710 - val_loss: 0.0672 - val_accuracy: 0.9721
Epoch 6/100
25743/25743 [==============================] - 82s 3ms/step - loss: 0.2195 - accuracy: 0.9712 - val_loss: 0.0650 - val_accuracy: 0.9722
Epoch 7/100
25743/25743 [==============================] - 82s 3ms/step - loss: 0.2171 - accuracy: 0.9714 - val_

In [42]:
y_pred12 = model12.predict_classes(X_test_mul_full)
confusionmatrix12 = confusion_matrix(Y_test_mul_full, y_pred12)
print(confusionmatrix12)

[[    23    330      4     24      0      0     43      0      0      0]
 [     0    333      1     14     12      1      0     41      4      1]
 [     2    378    112    438     48     23      5     73     29      1]
 [     8    401     68   4301    214     67     40    402    109     14]
 [     1    385      8    239   3171     40     29    330     71      0]
 [     2    329     80    368     57   4183      1     49     23     11]
 [   111     12     23    532   3913     38 386497    583    100      1]
 [     1    344      4     73     93      5      1   2232     20      0]
 [     0      0      0     21     25      5      0    150    124      0]
 [     0      0      0     25      1      0      0      0      2      7]]


In [43]:
print(classification_report(Y_test_mul_full, y_pred12, target_names=target_names))

                 precision    recall  f1-score   support

       Analysis       0.16      0.05      0.08       424
       Backdoor       0.13      0.82      0.23       407
            DoS       0.37      0.10      0.16      1109
       Exploits       0.71      0.76      0.74      5624
        Fuzzers       0.42      0.74      0.54      4274
        Generic       0.96      0.82      0.88      5103
         Normal       1.00      0.99      0.99    391810
Recconnaissanse       0.58      0.80      0.67      2773
      Shellcode       0.26      0.38      0.31       325
          Worms       0.20      0.20      0.20        35

       accuracy                           0.97    411884
      macro avg       0.48      0.57      0.48    411884
   weighted avg       0.98      0.97      0.98    411884

