In [1]:
from pycaret.classification import *
import numpy as np
import pandas as pd
import tensorflow as tf

#we will be using a full dataset, so our splitting will be done, and we will have 3 experiments
ds_full=pd.read_csv("D:\\Master Thesis Datasets\\UNSW-NB15 Source-Files\\UNSW-NB15 - CSV Files\\FULL.csv")
ds_full

Unnamed: 0         srcip  sport           dstip dsport proto state  \
0                 0    59.166.0.0  33661   149.171.126.9   1024   udp   CON   
1                 1    59.166.0.6   1464   149.171.126.7     53   udp   CON   
2                 2    59.166.0.5   3593   149.171.126.5     53   udp   CON   
3                 3    59.166.0.3  49664   149.171.126.0     53   udp   CON   
4                 4    59.166.0.0  32119   149.171.126.9    111   udp   CON   
...             ...           ...    ...             ...    ...   ...   ...   
2540038      440038    59.166.0.5  33094   149.171.126.7  43433   tcp   FIN   
2540039      440039    59.166.0.7  20848   149.171.126.4     21   tcp   CON   
2540040      440040    59.166.0.3  21511   149.171.126.9     21   tcp   CON   
2540041      440041    59.166.0.9  35433   149.171.126.0     80   tcp   CON   
2540042      440042  175.45.176.0  17293  149.171.126.17    110   tcp   CON   

              dur  sbytes  dbytes  sttl  dttl  sloss  dloss   service  \
0        0.036133     528     304    31    29      0      0         -   
1        0.001119     146     178    31    29      0      0       dns   
2        0.001209     132     164    31    29      0      0       dns   
3        0.001169     146     178    31    29      0      0       dns   
4        0.078339     568     312    31    29      0      0         -   
...           ...     ...     ...   ...   ...    ...    ...       ...   
2540038  0.087306     320    1828    31    29      1      2  ftp-data   
2540039  0.365058     456     346    31    29      2      2       ftp   
2540040  6.335154    1802    2088    31    29      7      9       ftp   
2540041  2.200934    3498  166054    31    29      2     57      http   
2540042  0.942984     574     676    62   252      5      6      pop3   

                 Sload          Dload  Spkts  Dpkts  swin  dwin       stcpb  \
0         87676.085940   50480.171880      4      4     0     0           0   
1        521894.531300  636282.375000      2      2     0     0           0   
2        436724.562500  542597.187500      2      2     0     0           0   
3        499572.250000  609067.562500      2      2     0     0           0   
4         43503.234380   23896.142580      4      4     0     0           0   
...                ...            ...    ...    ...   ...   ...         ...   
2540038   24465.671880  146610.765600      6      8   255   255  4035116044   
2540039    8743.816406    6333.240234      8      6   255   255  1529727621   
2540040    2204.839844    2549.582764     32     30   255   255   497208793   
2540041   12496.513670  598375.062500     58    116   255   255  1289728069   
2540042    4470.913574    5259.898438     12     12   255   255  3026824982   

              dtcpb  smeansz  dmeansz  trans_depth  res_bdy_len          Sjit  \
0                 0      132       76            0            0      9.891010   
1                 0       73       89            0            0      0.000000   
2                 0       66       82            0            0      0.000000   
3                 0       73       89            0            0      0.000000   
4                 0      142       78            0            0     29.682221   
...             ...      ...      ...          ...          ...           ...   
2540038   222196311       53      229            0            0   1221.136547   
2540039   185369967       57       58            0            0   3961.093354   
2540040   889904111       56       70            0            0  13233.728560   
2540041  3436097151       60     1432            1        79745   2868.893137   
2540042  3748412468       48       56            0            0   3903.523582   

                Djit       Stime       Ltime     Sintpkt     Dintpkt  \
0          10.682733  1421927414  1421927414    7.005000    7.564333   
1           0.000000  1421927414  1421927414    0.017000    0.013000   
2           0.000000  1421927414  1421927414 

In [2]:
ds_full.drop(columns="Unnamed: 0",inplace=True)
ds_full

srcip  sport           dstip dsport proto state       dur  \
0          59.166.0.0  33661   149.171.126.9   1024   udp   CON  0.036133   
1          59.166.0.6   1464   149.171.126.7     53   udp   CON  0.001119   
2          59.166.0.5   3593   149.171.126.5     53   udp   CON  0.001209   
3          59.166.0.3  49664   149.171.126.0     53   udp   CON  0.001169   
4          59.166.0.0  32119   149.171.126.9    111   udp   CON  0.078339   
...               ...    ...             ...    ...   ...   ...       ...   
2540038    59.166.0.5  33094   149.171.126.7  43433   tcp   FIN  0.087306   
2540039    59.166.0.7  20848   149.171.126.4     21   tcp   CON  0.365058   
2540040    59.166.0.3  21511   149.171.126.9     21   tcp   CON  6.335154   
2540041    59.166.0.9  35433   149.171.126.0     80   tcp   CON  2.200934   
2540042  175.45.176.0  17293  149.171.126.17    110   tcp   CON  0.942984   

         sbytes  dbytes  sttl  dttl  sloss  dloss   service          Sload  \
0           528     304    31    29      0      0         -   87676.085940   
1           146     178    31    29      0      0       dns  521894.531300   
2           132     164    31    29      0      0       dns  436724.562500   
3           146     178    31    29      0      0       dns  499572.250000   
4           568     312    31    29      0      0         -   43503.234380   
...         ...     ...   ...   ...    ...    ...       ...            ...   
2540038     320    1828    31    29      1      2  ftp-data   24465.671880   
2540039     456     346    31    29      2      2       ftp    8743.816406   
2540040    1802    2088    31    29      7      9       ftp    2204.839844   
2540041    3498  166054    31    29      2     57      http   12496.513670   
2540042     574     676    62   252      5      6      pop3    4470.913574   

                 Dload  Spkts  Dpkts  swin  dwin       stcpb       dtcpb  \
0         50480.171880      4      4     0     0           0           0   
1        636282.375000      2      2     0     0           0           0   
2        542597.187500      2      2     0     0           0           0   
3        609067.562500      2      2     0     0           0           0   
4         23896.142580      4      4     0     0           0           0   
...                ...    ...    ...   ...   ...         ...         ...   
2540038  146610.765600      6      8   255   255  4035116044   222196311   
2540039    6333.240234      8      6   255   255  1529727621   185369967   
2540040    2549.582764     32     30   255   255   497208793   889904111   
2540041  598375.062500     58    116   255   255  1289728069  3436097151   
2540042    5259.898438     12     12   255   255  3026824982  3748412468   

         smeansz  dmeansz  trans_depth  res_bdy_len          Sjit  \
0            132       76            0            0      9.891010   
1             73       89            0            0      0.000000   
2             66       82            0            0      0.000000   
3             73       89            0            0      0.000000   
4            142       78            0            0     29.682221   
...          ...      ...          ...          ...           ...   
2540038       53      229            0            0   1221.136547   
2540039       57       58            0            0   3961.093354   
2540040       56       70            0            0  13233.728560   
2540041       60     1432            1        79745   2868.893137   
2540042       48       56            0            0   3903.523582   

                Djit       Stime       Ltime     Sintpkt     Dintpkt  \
0          10.682733  1421927414  1421927414    7.005000    7.564333   
1           0.000000  1421927414  1421927414    0.017000    0.013000   
2           0.000000  1421927414  1421927414    0.043000    0.014000   
3           0.000000  1421927414  1421927414    0.005000    0.003000   
4          34.370340  1421927414  1421927414   21.00

In [3]:
# see how many duplicates
ds_full.duplicated().sum()
#remove these duplicates
ds_full_new = ds_full.drop_duplicates()
ds_full_new

srcip  sport           dstip dsport proto state       dur  \
0          59.166.0.0  33661   149.171.126.9   1024   udp   CON  0.036133   
1          59.166.0.6   1464   149.171.126.7     53   udp   CON  0.001119   
2          59.166.0.5   3593   149.171.126.5     53   udp   CON  0.001209   
3          59.166.0.3  49664   149.171.126.0     53   udp   CON  0.001169   
4          59.166.0.0  32119   149.171.126.9    111   udp   CON  0.078339   
...               ...    ...             ...    ...   ...   ...       ...   
2540035    59.166.0.1  38606   149.171.126.9     80   tcp   CON  0.564998   
2540037    59.166.0.1  38606   149.171.126.9     80   tcp   CON  0.564998   
2540038    59.166.0.5  33094   149.171.126.7  43433   tcp   FIN  0.087306   
2540041    59.166.0.9  35433   149.171.126.0     80   tcp   CON  2.200934   
2540042  175.45.176.0  17293  149.171.126.17    110   tcp   CON  0.942984   

         sbytes  dbytes  sttl  dttl  sloss  dloss   service          Sload  \
0           528     304    31    29      0      0         -   87676.085940   
1           146     178    31    29      0      0       dns  521894.531300   
2           132     164    31    29      0      0       dns  436724.562500   
3           146     178    31    29      0      0       dns  499572.250000   
4           568     312    31    29      0      0         -   43503.234380   
...         ...     ...   ...   ...    ...    ...       ...            ...   
2540035   14106  772406    31    29      2    262      http  198981.250000   
2540037   14106  772406    31    29      2    262         -  198981.250000   
2540038     320    1828    31    29      1      2  ftp-data   24465.671880   
2540041    3498  166054    31    29      2     57      http   12496.513670   
2540042     574     676    62   252      5      6      pop3    4470.913574   

                Dload  Spkts  Dpkts  swin  dwin       stcpb       dtcpb  \
0        5.048017e+04      4      4     0     0           0           0   
1        6.362824e+05      2      2     0     0           0           0   
2        5.425972e+05      2      2     0     0           0           0   
3        6.090676e+05      2      2     0     0           0           0   
4        2.389614e+04      4      4     0     0           0           0   
...               ...    ...    ...   ...   ...         ...         ...   
2540035  1.091598e+07    262    526   255   255   162243658   163257853   
2540037  1.091598e+07    262    526   255   255   162243658   163257853   
2540038  1.466108e+05      6      8   255   255  4035116044   222196311   
2540041  5.983751e+05     58    116   255   255  1289728069  3436097151   
2540042  5.259898e+03     12     12   255   255  3026824982  3748412468   

         smeansz  dmeansz  trans_depth  res_bdy_len         Sjit         Djit  \
0            132       76            0            0     9.891010    10.682733   
1             73       89            0            0     0.000000     0.000000   
2             66       82            0            0     0.000000     0.000000   
3             73       89            0            0     0.000000     0.000000   
4            142       78            0            0    29.682221    34.370340   
...          ...      ...          ...          ...          ...          ...   
2540035       54     1468            1       372266   116.321921    69.874077   
2540037       54     1468            1       372266   116.321921    69.874077   
2540038       53      229            0            0  1221.136547    30.096029   
2540041       60     1432            1        79745  2868.893137  1951.035944   
2540042       48       56            0            0  3903.523582    95.650531   

              Stime       Ltime    Sintpkt    Dintpkt    tcprtt    synack  \
0        1421927414  1421927414   7.005000   7.564333  0.000000  0.000000   
1        1421927414  1421927414   0.017000   0.013000  0.000000  0.000000   
2        1421927414  1421927414   0.043000   0.01

In [4]:
# replace "-" with "undefined"
ds_full_new['service'].replace('-', 'undefined', inplace=True)
ds_full_new

srcip  sport           dstip dsport proto state       dur  \
0          59.166.0.0  33661   149.171.126.9   1024   udp   CON  0.036133   
1          59.166.0.6   1464   149.171.126.7     53   udp   CON  0.001119   
2          59.166.0.5   3593   149.171.126.5     53   udp   CON  0.001209   
3          59.166.0.3  49664   149.171.126.0     53   udp   CON  0.001169   
4          59.166.0.0  32119   149.171.126.9    111   udp   CON  0.078339   
...               ...    ...             ...    ...   ...   ...       ...   
2540035    59.166.0.1  38606   149.171.126.9     80   tcp   CON  0.564998   
2540037    59.166.0.1  38606   149.171.126.9     80   tcp   CON  0.564998   
2540038    59.166.0.5  33094   149.171.126.7  43433   tcp   FIN  0.087306   
2540041    59.166.0.9  35433   149.171.126.0     80   tcp   CON  2.200934   
2540042  175.45.176.0  17293  149.171.126.17    110   tcp   CON  0.942984   

         sbytes  dbytes  sttl  dttl  sloss  dloss    service          Sload  \
0           528     304    31    29      0      0  undefined   87676.085940   
1           146     178    31    29      0      0        dns  521894.531300   
2           132     164    31    29      0      0        dns  436724.562500   
3           146     178    31    29      0      0        dns  499572.250000   
4           568     312    31    29      0      0  undefined   43503.234380   
...         ...     ...   ...   ...    ...    ...        ...            ...   
2540035   14106  772406    31    29      2    262       http  198981.250000   
2540037   14106  772406    31    29      2    262  undefined  198981.250000   
2540038     320    1828    31    29      1      2   ftp-data   24465.671880   
2540041    3498  166054    31    29      2     57       http   12496.513670   
2540042     574     676    62   252      5      6       pop3    4470.913574   

                Dload  Spkts  Dpkts  swin  dwin       stcpb       dtcpb  \
0        5.048017e+04      4      4     0     0           0           0   
1        6.362824e+05      2      2     0     0           0           0   
2        5.425972e+05      2      2     0     0           0           0   
3        6.090676e+05      2      2     0     0           0           0   
4        2.389614e+04      4      4     0     0           0           0   
...               ...    ...    ...   ...   ...         ...         ...   
2540035  1.091598e+07    262    526   255   255   162243658   163257853   
2540037  1.091598e+07    262    526   255   255   162243658   163257853   
2540038  1.466108e+05      6      8   255   255  4035116044   222196311   
2540041  5.983751e+05     58    116   255   255  1289728069  3436097151   
2540042  5.259898e+03     12     12   255   255  3026824982  3748412468   

         smeansz  dmeansz  trans_depth  res_bdy_len         Sjit         Djit  \
0            132       76            0            0     9.891010    10.682733   
1             73       89            0            0     0.000000     0.000000   
2             66       82            0            0     0.000000     0.000000   
3             73       89            0            0     0.000000     0.000000   
4            142       78            0            0    29.682221    34.370340   
...          ...      ...          ...          ...          ...          ...   
2540035       54     1468            1       372266   116.321921    69.874077   
2540037       54     1468            1       372266   116.321921    69.874077   
2540038       53      229            0            0  1221.136547    30.096029   
2540041       60     1432            1        79745  2868.893137  1951.035944   
2540042       48       56            0            0  3903.523582    95.650531   

              Stime       Ltime    Sintpkt    Dintpkt    tcprtt    synack  \
0        1421927414  1421927414   7.005000   7.564333  0.000000  0.000000   
1        1421927414  1421927414   0.017000   0.013000  0.000000  0.000000   
2        1421927414  1421927414   0.0

In [5]:
#change NaN to Normal
import math

ds_full_new['attack_cat'].replace(math.nan, 'Normal', inplace=True)
ds_full_new

srcip  sport           dstip dsport proto state       dur  \
0          59.166.0.0  33661   149.171.126.9   1024   udp   CON  0.036133   
1          59.166.0.6   1464   149.171.126.7     53   udp   CON  0.001119   
2          59.166.0.5   3593   149.171.126.5     53   udp   CON  0.001209   
3          59.166.0.3  49664   149.171.126.0     53   udp   CON  0.001169   
4          59.166.0.0  32119   149.171.126.9    111   udp   CON  0.078339   
...               ...    ...             ...    ...   ...   ...       ...   
2540035    59.166.0.1  38606   149.171.126.9     80   tcp   CON  0.564998   
2540037    59.166.0.1  38606   149.171.126.9     80   tcp   CON  0.564998   
2540038    59.166.0.5  33094   149.171.126.7  43433   tcp   FIN  0.087306   
2540041    59.166.0.9  35433   149.171.126.0     80   tcp   CON  2.200934   
2540042  175.45.176.0  17293  149.171.126.17    110   tcp   CON  0.942984   

         sbytes  dbytes  sttl  dttl  sloss  dloss    service          Sload  \
0           528     304    31    29      0      0  undefined   87676.085940   
1           146     178    31    29      0      0        dns  521894.531300   
2           132     164    31    29      0      0        dns  436724.562500   
3           146     178    31    29      0      0        dns  499572.250000   
4           568     312    31    29      0      0  undefined   43503.234380   
...         ...     ...   ...   ...    ...    ...        ...            ...   
2540035   14106  772406    31    29      2    262       http  198981.250000   
2540037   14106  772406    31    29      2    262  undefined  198981.250000   
2540038     320    1828    31    29      1      2   ftp-data   24465.671880   
2540041    3498  166054    31    29      2     57       http   12496.513670   
2540042     574     676    62   252      5      6       pop3    4470.913574   

                Dload  Spkts  Dpkts  swin  dwin       stcpb       dtcpb  \
0        5.048017e+04      4      4     0     0           0           0   
1        6.362824e+05      2      2     0     0           0           0   
2        5.425972e+05      2      2     0     0           0           0   
3        6.090676e+05      2      2     0     0           0           0   
4        2.389614e+04      4      4     0     0           0           0   
...               ...    ...    ...   ...   ...         ...         ...   
2540035  1.091598e+07    262    526   255   255   162243658   163257853   
2540037  1.091598e+07    262    526   255   255   162243658   163257853   
2540038  1.466108e+05      6      8   255   255  4035116044   222196311   
2540041  5.983751e+05     58    116   255   255  1289728069  3436097151   
2540042  5.259898e+03     12     12   255   255  3026824982  3748412468   

         smeansz  dmeansz  trans_depth  res_bdy_len         Sjit         Djit  \
0            132       76            0            0     9.891010    10.682733   
1             73       89            0            0     0.000000     0.000000   
2             66       82            0            0     0.000000     0.000000   
3             73       89            0            0     0.000000     0.000000   
4            142       78            0            0    29.682221    34.370340   
...          ...      ...          ...          ...          ...          ...   
2540035       54     1468            1       372266   116.321921    69.874077   
2540037       54     1468            1       372266   116.321921    69.874077   
2540038       53      229            0            0  1221.136547    30.096029   
2540041       60     1432            1        79745  2868.893137  1951.035944   
2540042       48       56            0            0  3903.523582    95.650531   

              Stime       Ltime    Sintpkt    Dintpkt    tcprtt    synack  \
0        1421927414  1421927414   7.005000   7.564333  0.000000  0.000000   
1        1421927414  1421927414   0.017000   0.013000  0.000000  0.000000   
2        1421927414  1421927414   0.0

In [6]:
# drop source IP and destination IP
ds_full_new.drop(columns=['srcip','dstip'],inplace=True)
ds_full_new

sport dsport proto state       dur  sbytes  dbytes  sttl  dttl  \
0        33661   1024   udp   CON  0.036133     528     304    31    29   
1         1464     53   udp   CON  0.001119     146     178    31    29   
2         3593     53   udp   CON  0.001209     132     164    31    29   
3        49664     53   udp   CON  0.001169     146     178    31    29   
4        32119    111   udp   CON  0.078339     568     312    31    29   
...        ...    ...   ...   ...       ...     ...     ...   ...   ...   
2540035  38606     80   tcp   CON  0.564998   14106  772406    31    29   
2540037  38606     80   tcp   CON  0.564998   14106  772406    31    29   
2540038  33094  43433   tcp   FIN  0.087306     320    1828    31    29   
2540041  35433     80   tcp   CON  2.200934    3498  166054    31    29   
2540042  17293    110   tcp   CON  0.942984     574     676    62   252   

         sloss  dloss    service          Sload         Dload  Spkts  Dpkts  \
0            0      0  undefined   87676.085940  5.048017e+04      4      4   
1            0      0        dns  521894.531300  6.362824e+05      2      2   
2            0      0        dns  436724.562500  5.425972e+05      2      2   
3            0      0        dns  499572.250000  6.090676e+05      2      2   
4            0      0  undefined   43503.234380  2.389614e+04      4      4   
...        ...    ...        ...            ...           ...    ...    ...   
2540035      2    262       http  198981.250000  1.091598e+07    262    526   
2540037      2    262  undefined  198981.250000  1.091598e+07    262    526   
2540038      1      2   ftp-data   24465.671880  1.466108e+05      6      8   
2540041      2     57       http   12496.513670  5.983751e+05     58    116   
2540042      5      6       pop3    4470.913574  5.259898e+03     12     12   

         swin  dwin       stcpb       dtcpb  smeansz  dmeansz  trans_depth  \
0           0     0           0           0      132       76            0   
1           0     0           0           0       73       89            0   
2           0     0           0           0       66       82            0   
3           0     0           0           0       73       89            0   
4           0     0           0           0      142       78            0   
...       ...   ...         ...         ...      ...      ...          ...   
2540035   255   255   162243658   163257853       54     1468            1   
2540037   255   255   162243658   163257853       54     1468            1   
2540038   255   255  4035116044   222196311       53      229            0   
2540041   255   255  1289728069  3436097151       60     1432            1   
2540042   255   255  3026824982  3748412468       48       56            0   

         res_bdy_len         Sjit         Djit       Stime       Ltime  \
0                  0     9.891010    10.682733  1421927414  1421927414   
1                  0     0.000000     0.000000  1421927414  1421927414   
2                  0     0.000000     0.000000  1421927414  1421927414   
3                  0     0.000000     0.000000  1421927414  1421927414   
4                  0    29.682221    34.370340  1421927414  1421927414   
...              ...          ...          ...         ...         ...   
2540035       372266   116.321921    69.874077  1424262068  1424262069   
2540037       372266   116.321921    69.874077  1424262068  1424262069   
2540038            0  1221.136547    30.096029  1424262068  1424262069   
2540041        79745  2868.893137  1951.035944  1424262067  1424262069   
2540042            0  3903.523582    95.650531  1424262068  1424262069   

           Sintpkt    Dintpkt    tcprtt    synack    ackdat  is_sm_ips_ports  \
0         7.005000   7.564333  0.000000  0.000000  0.000000                0   
1         0.017000   0.013000  0.000000  0.000000  0.000000                0   
2         0.043000   0.014000  0.000000  0.000000  0.000000                0   
3         0.0

In [7]:
#make the multiclass now
ds_full_multiclass = ds_full_new.drop(columns='label')
ds_full_multiclass

sport dsport proto state       dur  sbytes  dbytes  sttl  dttl  \
0        33661   1024   udp   CON  0.036133     528     304    31    29   
1         1464     53   udp   CON  0.001119     146     178    31    29   
2         3593     53   udp   CON  0.001209     132     164    31    29   
3        49664     53   udp   CON  0.001169     146     178    31    29   
4        32119    111   udp   CON  0.078339     568     312    31    29   
...        ...    ...   ...   ...       ...     ...     ...   ...   ...   
2540035  38606     80   tcp   CON  0.564998   14106  772406    31    29   
2540037  38606     80   tcp   CON  0.564998   14106  772406    31    29   
2540038  33094  43433   tcp   FIN  0.087306     320    1828    31    29   
2540041  35433     80   tcp   CON  2.200934    3498  166054    31    29   
2540042  17293    110   tcp   CON  0.942984     574     676    62   252   

         sloss  dloss    service          Sload         Dload  Spkts  Dpkts  \
0            0      0  undefined   87676.085940  5.048017e+04      4      4   
1            0      0        dns  521894.531300  6.362824e+05      2      2   
2            0      0        dns  436724.562500  5.425972e+05      2      2   
3            0      0        dns  499572.250000  6.090676e+05      2      2   
4            0      0  undefined   43503.234380  2.389614e+04      4      4   
...        ...    ...        ...            ...           ...    ...    ...   
2540035      2    262       http  198981.250000  1.091598e+07    262    526   
2540037      2    262  undefined  198981.250000  1.091598e+07    262    526   
2540038      1      2   ftp-data   24465.671880  1.466108e+05      6      8   
2540041      2     57       http   12496.513670  5.983751e+05     58    116   
2540042      5      6       pop3    4470.913574  5.259898e+03     12     12   

         swin  dwin       stcpb       dtcpb  smeansz  dmeansz  trans_depth  \
0           0     0           0           0      132       76            0   
1           0     0           0           0       73       89            0   
2           0     0           0           0       66       82            0   
3           0     0           0           0       73       89            0   
4           0     0           0           0      142       78            0   
...       ...   ...         ...         ...      ...      ...          ...   
2540035   255   255   162243658   163257853       54     1468            1   
2540037   255   255   162243658   163257853       54     1468            1   
2540038   255   255  4035116044   222196311       53      229            0   
2540041   255   255  1289728069  3436097151       60     1432            1   
2540042   255   255  3026824982  3748412468       48       56            0   

         res_bdy_len         Sjit         Djit       Stime       Ltime  \
0                  0     9.891010    10.682733  1421927414  1421927414   
1                  0     0.000000     0.000000  1421927414  1421927414   
2                  0     0.000000     0.000000  1421927414  1421927414   
3                  0     0.000000     0.000000  1421927414  1421927414   
4                  0    29.682221    34.370340  1421927414  1421927414   
...              ...          ...          ...         ...         ...   
2540035       372266   116.321921    69.874077  1424262068  1424262069   
2540037       372266   116.321921    69.874077  1424262068  1424262069   
2540038            0  1221.136547    30.096029  1424262068  1424262069   
2540041        79745  2868.893137  1951.035944  1424262067  1424262069   
2540042            0  3903.523582    95.650531  1424262068  1424262069   

           Sintpkt    Dintpkt    tcprtt    synack    ackdat  is_sm_ips_ports  \
0         7.005000   7.564333  0.000000  0.000000  0.000000                0   
1         0.017000   0.013000  0.000000  0.000000  0.000000                0   
2         0.043000   0.014000  0.000000  0.000000  0.000000                0   
3         0.0

In [8]:
pd.value_counts(ds_full_multiclass.attack_cat.values)

Normal              1959772
Exploits              27600
Generic               25378
 Fuzzers              17804
 Reconnaissance       11617
DoS                    5665
 Fuzzers               3991
Analysis               2185
Reconnaissance         1740
Backdoor               1684
 Shellcode             1288
Backdoors               300
Shellcode               223
Worms                   171
dtype: int64

In [9]:
#there are some typos, have to fix
ds_full_multiclass['attack_cat'] = ds_full_multiclass['attack_cat'].str.strip()
pd.value_counts(ds_full_multiclass.attack_cat.values)

Normal            1959772
Exploits            27600
Generic             25378
Fuzzers             21795
Reconnaissance      13357
DoS                  5665
Analysis             2185
Backdoor             1684
Shellcode            1511
Backdoors             300
Worms                 171
dtype: int64

In [10]:
ds_full_multiclass['attack_cat'].replace('Backdoors','Backdoor',inplace=True)
pd.value_counts(ds_full_multiclass.attack_cat.values)

Normal            1959772
Exploits            27600
Generic             25378
Fuzzers             21795
Reconnaissance      13357
DoS                  5665
Analysis             2185
Backdoor             1984
Shellcode            1511
Worms                 171
dtype: int64

In [11]:
pd.unique(ds_full_multiclass.attack_cat)

array(['Normal', 'Exploits', 'Reconnaissance', 'DoS', 'Generic',
       'Shellcode', 'Fuzzers', 'Worms', 'Backdoor', 'Analysis'],
      dtype=object)

In [13]:
#now we should remove whitespaces everywhere
ds_full_multiclass.isnull().sum()

sport                     0
dsport                    0
proto                     0
state                     0
dur                       0
sbytes                    0
dbytes                    0
sttl                      0
dttl                      0
sloss                     0
dloss                     0
service                   0
Sload                     0
Dload                     0
Spkts                     0
Dpkts                     0
swin                      0
dwin                      0
stcpb                     0
dtcpb                     0
smeansz                   0
dmeansz                   0
trans_depth               0
res_bdy_len               0
Sjit                      0
Djit                      0
Stime                     0
Ltime                     0
Sintpkt                   0
Dintpkt                   0
tcprtt                    0
synack                    0
ackdat                    0
is_sm_ips_ports           0
ct_state_ttl              0
ct_flw_http_mthd    

In [16]:
pd.unique(ds_full_multiclass.ct_flw_http_mthd)

array([ 0.,  1.,  2.,  4., 14.,  8.,  6., 12., 10.,  3.,  5., 36.,  9.,
       16., 25., 30.])

In [15]:
ds_full_multiclass['ct_flw_http_mthd'].replace(math.nan, float(0),inplace=True)

In [19]:
pd.unique(ds_full_multiclass.is_ftp_login)

array([0., 1., 2., 4.])

In [18]:
ds_full_multiclass['is_ftp_login'].replace(math.nan, float(0),inplace=True)

In [22]:
pd.unique(ds_full_multiclass.ct_ftp_cmd)

array(['0', '1', 6, '2', '4', 8, 5, '3'], dtype=object)

In [21]:
ds_full_multiclass['ct_ftp_cmd'].replace(0, '0', inplace=True)
ds_full_multiclass['ct_ftp_cmd'].replace(' ', '0', inplace=True)
ds_full_multiclass['ct_ftp_cmd'].replace(1, '1', inplace=True)
ds_full_multiclass['ct_ftp_cmd'].replace(2, '2', inplace=True)
ds_full_multiclass['ct_ftp_cmd'].replace(3, '3', inplace=True)
ds_full_multiclass['ct_ftp_cmd'].replace(4, '4', inplace=True)

In [23]:
#now the multiclass dataset is ready, but we need to make the starting columns
dsp_tr_multiclass_full=setup(data = ds_full_multiclass,
             target = 'attack_cat',train_size=0.8,
             numeric_imputation = 'mean',
             categorical_features = ['proto','service','state'],
             numeric_features=['dur','Spkts','Dpkts','sbytes','dbytes','sttl','dttl','Sload','Dload','sloss','dloss','Sintpkt','Dintpkt','Sjit','Djit','swin','stcpb','dtcpb','dwin','tcprtt','synack','ackdat','smeansz','dmeansz','trans_depth','res_bdy_len','ct_srv_src','ct_state_ttl','ct_dst_ltm','ct_src_dport_ltm','ct_dst_sport_ltm',
                               'ct_dst_src_ltm','is_ftp_login','ct_ftp_cmd','ct_flw_http_mthd','ct_src_ ltm','ct_srv_dst','is_sm_ips_ports'],
                ignore_features=['dsport','sport','Stime','Ltime'],
             normalize=True,normalize_method='minmax',
             silent = True, fold_shuffle=True)

In [24]:
X_train_mul_full=get_config('X_train')
X_test_mul_full = get_config('X_test')
Y_train_mul_full = get_config('y_train')
Y_test_mul_full = get_config('y_test')

In [25]:
X_train_mul_full

dur    sbytes    dbytes      sttl      dttl     sloss  \
2263443  5.361550e-07  0.000042  0.000021  0.121569  0.114173  0.000000   
1125914  1.310069e-05  0.000287  0.003922  0.121569  0.114173  0.001374   
1919486  2.370759e-06  0.000113  0.000112  0.121569  0.114173  0.000785   
936364   1.358881e-06  0.000178  0.001325  0.121569  0.114173  0.001374   
688887   1.144796e-04  0.000116  0.000694  0.121569  0.114173  0.000589   
...               ...       ...       ...       ...       ...       ...   
218903   1.222311e-07  0.000011  0.000012  0.121569  0.114173  0.000000   
869288   2.059719e-06  0.000113  0.000112  0.121569  0.114173  0.000785   
330374   2.422314e-06  0.000202  0.001971  0.121569  0.114173  0.001374   
2516421  8.588404e-05  0.000184  0.000018  0.996078  0.992126  0.000392   
1667398  1.198411e-07  0.000011  0.000012  0.121569  0.114173  0.000000   

            dloss     Sload     Dload     Spkts  ...  service_ftp-data  \
2263443  0.000000  0.000121  0.006185  0.000392  ...               0.0   
1125914  0.004923  0.000045  0.062869  0.006471  ...               0.0   
1919486  0.000729  0.000093  0.009527  0.001569  ...               0.0   
936364   0.002371  0.000266  0.202685  0.003725  ...               0.0   
688887   0.000912  0.000002  0.001220  0.001176  ...               0.0   
...           ...       ...       ...       ...  ...               ...   
218903   0.000000  0.000091  0.010590  0.000196  ...               0.0   
869288   0.000729  0.000107  0.010966  0.001569  ...               0.0   
330374   0.002918  0.000170  0.169706  0.004314  ...               0.0   
2516421  0.000182  0.000004  0.000038  0.000980  ...               0.0   
1667398  0.000000  0.000093  0.010801  0.000196  ...               0.0   

         service_http  service_irc  service_pop3  service_radius  \
2263443           0.0          0.0           0.0             0.0   
1125914           0.0          0.0           0.0             0.0   
1919486           0.0          0.0           0.0             0.0   
936364            0.0          0.0           0.0             0.0   
688887            0.0          0.0           0.0             0.0   
...               ...          ...           ...             ...   
218903            0.0          0.0           0.0             0.0   
869288            0.0          0.0           0.0             0.0   
330374            0.0          0.0           0.0             0.0   
2516421           0.0          0.0           0.0             0.0   
1667398           0.0          0.0           0.0             0.0   

         service_smtp  service_snmp  service_ssh  service_ssl  \
2263443           0.0           0.0          0.0          0.0   
1125914           0.0           0.0          0.0          0.0   
1919486           0.0           0.0          0.0          0.0   
936364            0.0           0.0          0.0          0.0   
688887            0.0           0.0          0.0          0.0   
...               ...           ...          ...          ...   
218903            0.0           0.0          0.0          0.0   
869288            0.0           0.0          0.0          0.0   
330374            0.0           0.0          0.0          0.0   
2516421           0.0           0.0          0.0          0.0   
1667398           0.0           0.0          0.0          0.0   

         service_undefined  
2263443                1.0  
1125914                1.0  
1919486                1.0  
936364                 1.0  
688887                 1.0  
...                    ...  
218903                 0.0  
869288                 1.0  
330374                 1.0  
2516421                1.0  
1667398                0.0  

[1647534 rows x 200 columns]

In [26]:
Y_train_mul_full

2263443    6
1125914    6
1919486    6
936364     6
688887     6
          ..
218903     6
869288     6
330374     6
2516421    6
1667398    6
Name: attack_cat, Length: 1647534, dtype: int32

In [27]:
from tensorflow.python.keras.layers import Activation
from keras.optimizers import SGD
from keras.models import Sequential
from keras.layers import Dense
from keras.layers.advanced_activations import PReLU
from keras.layers import Dropout
from keras.callbacks import EarlyStopping
act1 = PReLU(alpha_initializer='zeros', weights=None)
model1 = Sequential()
# define the NN architecture and activation function

model1.add(Dense(496, input_dim=200, activation=Activation(act1)))
model1.add(Dropout(0.1))
model1.add(Dense(248, activation='relu'))
model1.add(Dropout(0.1))
model1.add(Dense(124, activation='relu'))
model1.add(Dropout(0.1))
model1.add(Dense(62, activation='relu'))
model1.add(Dropout(0.1))
model1.add(Dense(10))
model1.add(Activation('softmax'))

sgd =SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
model1.compile(loss='sparse_categorical_crossentropy', optimizer=sgd, metrics= ['accuracy'])
es = EarlyStopping(monitor='val_accuracy', mode='max', min_delta=0.0001,patience=5) ## early stopping
model1.fit(X_train_mul_full, Y_train_mul_full, validation_data=(X_test_mul_full, Y_test_mul_full), epochs=100, batch_size=64, callbacks=[es])

Epoch 1/100
25743/25743 [==============================] - 91s 4ms/step - loss: 0.0762 - accuracy: 0.9708 - val_loss: 0.0641 - val_accuracy: 0.9741
Epoch 2/100
25743/25743 [==============================] - 93s 4ms/step - loss: 0.0649 - accuracy: 0.9739 - val_loss: 0.0624 - val_accuracy: 0.9745
Epoch 3/100
25743/25743 [==============================] - 88s 3ms/step - loss: 0.0628 - accuracy: 0.9745 - val_loss: 0.0600 - val_accuracy: 0.9755
Epoch 4/100
25743/25743 [==============================] - 86s 3ms/step - loss: 0.0615 - accuracy: 0.9749 - val_loss: 0.0612 - val_accuracy: 0.9745
Epoch 5/100
25743/25743 [==============================] - 85s 3ms/step - loss: 0.0606 - accuracy: 0.9752 - val_loss: 0.0598 - val_accuracy: 0.9752
Epoch 6/100
25743/25743 [==============================] - 85s 3ms/step - loss: 0.0597 - accuracy: 0.9755 - val_loss: 0.0589 - val_accuracy: 0.9757
Epoch 7/100
25743/25743 [==============================] - 85s 3ms/step - loss: 0.0593 - accuracy: 0.9756 - val_

In [28]:
#training accuracy
train_acc1 = model1.evaluate(X_train_mul_full, Y_train_mul_full, verbose=0)
print("%s: %.2f%%" % (model1.metrics_names[1], train_acc1[1] * 100))
#calculate the test accuracy using evaluate function
test_acc1 = model1.evaluate(X_test_mul_full, Y_test_mul_full, verbose=0)
print("%s: %.2f%%" % (model1.metrics_names[1], test_acc1[1] * 100))

accuracy: 97.91%
accuracy: 97.87%


In [29]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score, recall_score, f1_score, roc_auc_score
y_pred1 = model1.predict_classes(X_test_mul_full)
pred_accuracy1 = accuracy_score(Y_test_mul_full, y_pred1)
pred_accuracy1

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).


0.9787488710413612

In [30]:
# Precision
precision1 = precision_score(Y_test_mul_full, y_pred1, average='weighted')
print('Precision : %f' % precision1)
#recall
recall1 = recall_score(Y_test_mul_full, y_pred1, average='weighted')
print('Recall: %f' % recall1)
# f1-score
f1_1 = f1_score(Y_test_mul_full, y_pred1, average='weighted')
print('F1 score: %f' % f1_1)

Precision : 0.975495
Recall: 0.978749
F1 score: 0.976460


In [31]:
from sklearn.metrics import confusion_matrix
# confusion matrix
confusionmatrix1 = confusion_matrix(Y_test_mul_full, y_pred1)
print(confusionmatrix1)

[[     7     20      4     25    310      0     89      0      0      0]
 [     8     11     10     49    261      3     11     41      0      0]
 [     9      8     28    496    359     53     62     62     15      0]
 [     9     21     21   4232    459     70    345    427     12      0]
 [    11     20      2    127   1560     20   2536    123     12      0]
 [     0      0      6    406    356   4175     52     38      5      0]
 [     0      0      0    190    540     11 390912    180     13      0]
 [     0      0      1    102    309      4    172   2122      0      0]
 [     0      0      0     22     20      4     34    140     84      0]
 [     0      0      0     27      3      5      2      1      0      0]]


In [32]:
from sklearn.metrics import classification_report
target_names=['Analysis','Backdoor','DoS','Exploits','Fuzzers','Generic','Normal','Recconnaissanse','Shellcode','Worms']
print(classification_report(Y_test_mul_full, y_pred1, target_names=target_names))

                 precision    recall  f1-score   support

       Analysis       0.16      0.02      0.03       455
       Backdoor       0.14      0.03      0.05       394
            DoS       0.39      0.03      0.05      1092
       Exploits       0.75      0.76      0.75      5596
        Fuzzers       0.37      0.35      0.36      4411
        Generic       0.96      0.83      0.89      5038
         Normal       0.99      1.00      0.99    391846
Recconnaissanse       0.68      0.78      0.73      2710
      Shellcode       0.60      0.28      0.38       304
          Worms       0.00      0.00      0.00        38

       accuracy                           0.98    411884
      macro avg       0.50      0.41      0.42    411884
   weighted avg       0.98      0.98      0.98    411884



In [33]:
roc1 = roc_auc_score(Y_test_mul_full, model1.predict(X_test_mul_full), average='weighted', multi_class='ovr')
print('ROC AUC score: %f' % roc1)

ROC AUC score: 0.998671


In [34]:
#FNR= 16.48%

In [3]:
#now we select features
#now the multiclass dataset is ready, but we need to make the starting columns
dsp_tr_multiclass_selected=setup(data = ds_full_multiclass,
             target = 'attack_cat',train_size=0.8,
             numeric_imputation = 'mean',
             categorical_features = ['proto','service','state'],
             numeric_features=['dur','Spkts','Dpkts','sbytes','dbytes','sttl','dttl','Sload','Dload','sloss','dloss','Sintpkt','Dintpkt','Sjit','Djit','swin','stcpb','dtcpb','dwin','tcprtt','synack','ackdat','smeansz','dmeansz','trans_depth','res_bdy_len','ct_srv_src','ct_state_ttl','ct_dst_ltm','ct_src_dport_ltm','ct_dst_sport_ltm',
                               'ct_dst_src_ltm','is_ftp_login','ct_ftp_cmd','ct_flw_http_mthd','ct_src_ ltm','ct_srv_dst','is_sm_ips_ports'],
                ignore_features=['dsport','sport','Stime','Ltime'],
             normalize=True,normalize_method='minmax',feature_selection=True,feature_selection_threshold=0.2,
             silent = True, fold_shuffle=True)

In [36]:
#saving the previous datasets
X_train_mul_full.to_csv("D:\\Master Thesis Datasets\\X_train_mul_full.csv")
Y_train_mul_full.to_csv("D:\\Master Thesis Datasets\\Y_train_mul_full.csv")
X_test_mul_full.to_csv("D:\\Master Thesis Datasets\\X_test_mul_full.csv")
Y_test_mul_full.to_csv("D:\\Master Thesis Datasets\\Y_test_mul_full.csv")

In [39]:
ds_full_multiclass.to_csv("D:\\Master Thesis Datasets\\ds_full_multiclass.csv")

In [2]:
from pycaret.classification import *
import numpy as np
import pandas as pd
import tensorflow as tf
ds_full_multiclass=pd.read_csv("D:\\Master Thesis Datasets\\ds_full_multiclass.csv",index_col="Unnamed: 0")
ds_full_multiclass

sport dsport proto state       dur  sbytes  dbytes  sttl  dttl  \
0        33661   1024   udp   CON  0.036133     528     304    31    29   
1         1464     53   udp   CON  0.001119     146     178    31    29   
2         3593     53   udp   CON  0.001209     132     164    31    29   
3        49664     53   udp   CON  0.001169     146     178    31    29   
4        32119    111   udp   CON  0.078339     568     312    31    29   
...        ...    ...   ...   ...       ...     ...     ...   ...   ...   
2540035  38606     80   tcp   CON  0.564998   14106  772406    31    29   
2540037  38606     80   tcp   CON  0.564998   14106  772406    31    29   
2540038  33094  43433   tcp   FIN  0.087306     320    1828    31    29   
2540041  35433     80   tcp   CON  2.200934    3498  166054    31    29   
2540042  17293    110   tcp   CON  0.942984     574     676    62   252   

         sloss  dloss    service          Sload         Dload  Spkts  Dpkts  \
0            0      0  undefined   87676.085940  5.048017e+04      4      4   
1            0      0        dns  521894.531300  6.362824e+05      2      2   
2            0      0        dns  436724.562500  5.425972e+05      2      2   
3            0      0        dns  499572.250000  6.090676e+05      2      2   
4            0      0  undefined   43503.234380  2.389614e+04      4      4   
...        ...    ...        ...            ...           ...    ...    ...   
2540035      2    262       http  198981.250000  1.091598e+07    262    526   
2540037      2    262  undefined  198981.250000  1.091598e+07    262    526   
2540038      1      2   ftp-data   24465.671880  1.466108e+05      6      8   
2540041      2     57       http   12496.513670  5.983751e+05     58    116   
2540042      5      6       pop3    4470.913574  5.259898e+03     12     12   

         swin  dwin       stcpb       dtcpb  smeansz  dmeansz  trans_depth  \
0           0     0           0           0      132       76            0   
1           0     0           0           0       73       89            0   
2           0     0           0           0       66       82            0   
3           0     0           0           0       73       89            0   
4           0     0           0           0      142       78            0   
...       ...   ...         ...         ...      ...      ...          ...   
2540035   255   255   162243658   163257853       54     1468            1   
2540037   255   255   162243658   163257853       54     1468            1   
2540038   255   255  4035116044   222196311       53      229            0   
2540041   255   255  1289728069  3436097151       60     1432            1   
2540042   255   255  3026824982  3748412468       48       56            0   

         res_bdy_len         Sjit         Djit       Stime       Ltime  \
0                  0     9.891010    10.682733  1421927414  1421927414   
1                  0     0.000000     0.000000  1421927414  1421927414   
2                  0     0.000000     0.000000  1421927414  1421927414   
3                  0     0.000000     0.000000  1421927414  1421927414   
4                  0    29.682221    34.370340  1421927414  1421927414   
...              ...          ...          ...         ...         ...   
2540035       372266   116.321921    69.874077  1424262068  1424262069   
2540037       372266   116.321921    69.874077  1424262068  1424262069   
2540038            0  1221.136547    30.096029  1424262068  1424262069   
2540041        79745  2868.893137  1951.035944  1424262067  1424262069   
2540042            0  3903.523582    95.650531  1424262068  1424262069   

           Sintpkt    Dintpkt    tcprtt    synack    ackdat  is_sm_ips_ports  \
0         7.005000   7.564333  0.000000  0.000000  0.000000                0   
1         0.017000   0.013000  0.000000  0.000000  0.000000                0   
2         0.043000   0.014000  0.000000  0.000000  0.000000                0   
3         0.0

In [4]:
X_train_for_columns=get_config('X_train')
X_train_for_columns.columns

Index(['service_dns', 'service_ftp-data', 'sbytes', 'Sintpkt', 'stcpb',
       'sloss', 'trans_depth', 'state_CON', 'res_bdy_len', 'smeansz',
       'state_INT', 'sttl', 'proto_udp', 'dmeansz', 'ct_src_dport_ltm',
       'ct_dst_src_ltm', 'dtcpb', 'dur', 'ct_src_ ltm', 'ct_srv_src', 'tcprtt',
       'ct_state_ttl', 'service_undefined', 'ct_dst_sport_ltm', 'Djit',
       'dloss', 'ct_flw_http_mthd', 'service_http', 'dbytes', 'ackdat',
       'state_FIN', 'proto_ospf', 'proto_sctp', 'Sjit', 'Sload', 'ct_dst_ltm',
       'Spkts', 'Dintpkt', 'synack', 'Dpkts', 'ct_srv_dst', 'Dload', 'dttl',
       'proto_unas'],
      dtype='object')

In [5]:
X_train_mul_full=pd.read_csv("D:\\Master Thesis Datasets\\X_train_mul_full.csv",index_col="Unnamed: 0")
Y_train_mul_full=pd.read_csv("D:\\Master Thesis Datasets\\Y_train_mul_full.csv",index_col="Unnamed: 0")
X_test_mul_full=pd.read_csv("D:\\Master Thesis Datasets\\X_test_mul_full.csv",index_col="Unnamed: 0")
Y_test_mul_full=pd.read_csv("D:\\Master Thesis Datasets\\Y_test_mul_full.csv",index_col="Unnamed: 0")

In [6]:
columns_to_use=['service_dns', 'service_ftp-data', 'sbytes', 'Sintpkt', 'stcpb',
       'sloss', 'trans_depth', 'state_CON', 'res_bdy_len', 'smeansz',
       'state_INT', 'sttl', 'proto_udp', 'dmeansz', 'ct_src_dport_ltm',
       'ct_dst_src_ltm', 'dtcpb', 'dur', 'ct_src_ ltm', 'ct_srv_src', 'tcprtt',
       'ct_state_ttl', 'service_undefined', 'ct_dst_sport_ltm', 'Djit',
       'dloss', 'ct_flw_http_mthd', 'service_http', 'dbytes', 'ackdat',
       'state_FIN', 'proto_ospf', 'proto_sctp', 'Sjit', 'Sload', 'ct_dst_ltm',
       'Spkts', 'Dintpkt', 'synack', 'Dpkts', 'ct_srv_dst', 'Dload', 'dttl',
       'proto_unas']

In [7]:
X_train_mul_selected=X_train_mul_full[columns_to_use]
X_train_mul_selected.shape

(1647534, 44)

In [8]:
X_test_mul_selected=X_test_mul_full[columns_to_use]
X_test_mul_selected.shape

(411884, 44)

In [9]:
Y_test_mul_full.shape

(411884, 1)

In [10]:
Y_train_mul_full.shape

(1647534, 1)

In [11]:
#now we train using these features
from tensorflow.python.keras.layers import Activation
from keras.optimizers import SGD
from keras.models import Sequential
from keras.layers import Dense
from keras.layers.advanced_activations import PReLU
from keras.layers import Dropout
from keras.callbacks import EarlyStopping
act2 = PReLU(alpha_initializer='zeros', weights=None)
model2 = Sequential()
# define the NN architecture and activation function

model2.add(Dense(496, input_dim=44, activation=Activation(act2)))
model2.add(Dropout(0.1))
model2.add(Dense(248, activation='relu'))
model2.add(Dropout(0.1))
model2.add(Dense(124, activation='relu'))
model2.add(Dropout(0.1))
model2.add(Dense(62, activation='relu'))
model2.add(Dropout(0.1))
model2.add(Dense(10))
model2.add(Activation('softmax'))

sgd =SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
model2.compile(loss='sparse_categorical_crossentropy', optimizer=sgd, metrics= ['accuracy'])
es = EarlyStopping(monitor='val_accuracy', mode='max', min_delta=0.0001,patience=5) ## early stopping
model2.fit(X_train_mul_selected, Y_train_mul_full, validation_data=(X_test_mul_selected, Y_test_mul_full), epochs=100, batch_size=64, callbacks=[es])

Epoch 1/100
25743/25743 [==============================] - 87s 3ms/step - loss: 0.0761 - accuracy: 0.9712 - val_loss: 0.0645 - val_accuracy: 0.9739
Epoch 2/100
25743/25743 [==============================] - 96s 4ms/step - loss: 0.0649 - accuracy: 0.9739 - val_loss: 0.0613 - val_accuracy: 0.9751
Epoch 3/100
25743/25743 [==============================] - 87s 3ms/step - loss: 0.0628 - accuracy: 0.9745 - val_loss: 0.0601 - val_accuracy: 0.9756
Epoch 4/100
25743/25743 [==============================] - 88s 3ms/step - loss: 0.0615 - accuracy: 0.9749 - val_loss: 0.0597 - val_accuracy: 0.9752
Epoch 5/100
25743/25743 [==============================] - 85s 3ms/step - loss: 0.0606 - accuracy: 0.9752 - val_loss: 0.0596 - val_accuracy: 0.9758
Epoch 6/100
25743/25743 [==============================] - 89s 3ms/step - loss: 0.0598 - accuracy: 0.9756 - val_loss: 0.0575 - val_accuracy: 0.9767
Epoch 7/100
25743/25743 [==============================] - 83s 3ms/step - loss: 0.0591 - accuracy: 0.9758 - val_

In [12]:
#training accuracy
train_acc2 = model2.evaluate(X_train_mul_selected, Y_train_mul_full, verbose=0)
print("%s: %.2f%%" % (model2.metrics_names[1], train_acc2[1] * 100))
#calculate the test accuracy using evaluate function
test_acc2 = model2.evaluate(X_test_mul_selected, Y_test_mul_full, verbose=0)
print("%s: %.2f%%" % (model2.metrics_names[1], test_acc2[1] * 100))

accuracy: 97.71%
accuracy: 97.70%


In [13]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score, recall_score, f1_score, roc_auc_score
y_pred2 = model2.predict_classes(X_test_mul_selected)
pred_accuracy2 = accuracy_score(Y_test_mul_full, y_pred2)
pred_accuracy2

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).


0.9769668158996222

In [14]:
# Precision
precision2 = precision_score(Y_test_mul_full, y_pred2, average='weighted')
print('Precision : %f' % precision2)
#recall
recall2 = recall_score(Y_test_mul_full, y_pred2, average='weighted')
print('Recall: %f' % recall2)
# f1-score
f1_2 = f1_score(Y_test_mul_full, y_pred2, average='weighted')
print('F1 score: %f' % f1_2)

Precision : 0.974396
Recall: 0.976967
F1 score: 0.974772


In [15]:
from sklearn.metrics import confusion_matrix
# confusion matrix
confusionmatrix2 = confusion_matrix(Y_test_mul_full, y_pred2)
print(confusionmatrix2)

[[     0      0     15    167    131      0     82     60      0      0]
 [     0      0     19    138    116      6     16     99      0      0]
 [     0      0     28    625    144     62     42    173     18      0]
 [     0      0     28   4218    212    111    163    849     15      0]
 [     0      0     14    413   1346     63   2101    456     18      0]
 [     0      0      8    518    164   4186     31    125      6      0]
 [     0      0      3    393    582     47 390217    586     18      0]
 [     0      0      5    149    129      8     91   2328      0      0]
 [     0      0      0     13     17      5     17    178     74      0]
 [     0      0      0     25      0      7      0      5      1      0]]


In [16]:
from sklearn.metrics import classification_report
target_names=['Analysis','Backdoor','DoS','Exploits','Fuzzers','Generic','Normal','Recconnaissanse','Shellcode','Worms']
print(classification_report(Y_test_mul_full, y_pred2, target_names=target_names))

                 precision    recall  f1-score   support

       Analysis       0.00      0.00      0.00       455
       Backdoor       0.00      0.00      0.00       394
            DoS       0.23      0.03      0.05      1092
       Exploits       0.63      0.75      0.69      5596
        Fuzzers       0.47      0.31      0.37      4411
        Generic       0.93      0.83      0.88      5038
         Normal       0.99      1.00      0.99    391846
Recconnaissanse       0.48      0.86      0.62      2710
      Shellcode       0.49      0.24      0.33       304
          Worms       0.00      0.00      0.00        38

       accuracy                           0.98    411884
      macro avg       0.42      0.40      0.39    411884
   weighted avg       0.97      0.98      0.97    411884



In [17]:
roc2 = roc_auc_score(Y_test_mul_full, model2.predict(X_test_mul_selected), average='weighted', multi_class='ovr')
print('ROC AUC score: %f' % roc2)

ROC AUC score: 0.998491


In [37]:
#FNR=12.69%

In [29]:
from sklearn.utils import compute_class_weight
weights_multi=compute_class_weight('balanced',np.unique(Y_train_mul_full.attack_cat), y=Y_train_mul_full.values.reshape(-1))
weights_multi

array([9.52331792e+01, 1.03618491e+02, 3.60274218e+01, 7.48742956e+00,
       9.47730097e+00, 8.09997050e+00, 1.05077280e-01, 1.54741617e+01,
       1.36498260e+02, 1.23874737e+03])

In [27]:
np.unique(Y_train_mul_full.attack_cat)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [31]:
act3= PReLU(alpha_initializer='zeros', weights=None)
model3 = Sequential()
# define the NN architecture and activation function

model3.add(Dense(496, input_dim=44, activation=Activation(act3)))
model3.add(Dropout(0.1))
model3.add(Dense(248, activation='relu'))
model3.add(Dropout(0.1))
model3.add(Dense(124, activation='relu'))
model3.add(Dropout(0.1))
model3.add(Dense(62, activation='relu'))
model3.add(Dropout(0.1))
model3.add(Dense(10))
model3.add(Activation('softmax'))

sgd =SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
model3.compile(loss='sparse_categorical_crossentropy', optimizer=sgd, metrics= ['accuracy'])
es = EarlyStopping(monitor='val_accuracy', mode='max', min_delta=0.0001,patience=5) ## early stopping
model3.fit(X_train_mul_selected, Y_train_mul_full, validation_data=(X_test_mul_selected, Y_test_mul_full), epochs=100, batch_size=64, callbacks=[es], class_weight={0:9,1:10,2:5,3:3,4:3.5,5:3,6:1,7:4,8:15,9:20})

Epoch 1/100
25743/25743 [==============================] - 85s 3ms/step - loss: 0.2635 - accuracy: 0.9682 - val_loss: 0.0725 - val_accuracy: 0.9711
Epoch 2/100
25743/25743 [==============================] - 86s 3ms/step - loss: 0.2380 - accuracy: 0.9698 - val_loss: 0.0678 - val_accuracy: 0.9707
Epoch 3/100
25743/25743 [==============================] - 84s 3ms/step - loss: 0.2303 - accuracy: 0.9704 - val_loss: 0.0736 - val_accuracy: 0.9707
Epoch 4/100
25743/25743 [==============================] - 84s 3ms/step - loss: 0.2263 - accuracy: 0.9706 - val_loss: 0.0648 - val_accuracy: 0.9728
Epoch 5/100
25743/25743 [==============================] - 87s 3ms/step - loss: 0.2226 - accuracy: 0.9710 - val_loss: 0.0690 - val_accuracy: 0.9721
Epoch 6/100
25743/25743 [==============================] - 86s 3ms/step - loss: 0.2201 - accuracy: 0.9712 - val_loss: 0.0657 - val_accuracy: 0.9720
Epoch 7/100
25743/25743 [==============================] - 85s 3ms/step - loss: 0.2171 - accuracy: 0.9715 - val_

In [32]:
#training accuracy
train_acc3 = model3.evaluate(X_train_mul_selected, Y_train_mul_full, verbose=0)
print("%s: %.2f%%" % (model3.metrics_names[1], train_acc3[1] * 100))
#calculate the test accuracy using evaluate function
test_acc3 = model3.evaluate(X_test_mul_selected, Y_test_mul_full, verbose=0)
print("%s: %.2f%%" % (model3.metrics_names[1], test_acc3[1] * 100))

accuracy: 97.25%
accuracy: 97.25%


In [33]:
y_pred3 = model3.predict_classes(X_test_mul_selected)
pred_accuracy3 = accuracy_score(Y_test_mul_full, y_pred3)
pred_accuracy3

0.9725262452535179

In [34]:
# Precision
precision3 = precision_score(Y_test_mul_full, y_pred3, average='weighted')
print('Precision : %f' % precision3)
#recall
recall3 = recall_score(Y_test_mul_full, y_pred3, average='weighted')
print('Recall: %f' % recall3)
# f1-score
f1_3 = f1_score(Y_test_mul_full, y_pred3, average='weighted')
print('F1 score: %f' % f1_3)

Precision : 0.982004
Recall: 0.972526
F1 score: 0.975565


In [35]:
# confusion matrix
confusionmatrix3 = confusion_matrix(Y_test_mul_full, y_pred3)
print(confusionmatrix3)

[[    14    349      0     23      0      0     69      0      0      0]
 [     0    322      0     11      9      0      3     46      0      3]
 [     0    376     30    456     45     52     12     92     28      1]
 [     8    442     13   3964    209     73     53    682    142     10]
 [     0    387      2    202   3076    103      8    443    190      0]
 [     1    339      1    390     41   4154      6     59     32     15]
 [    38     11      6    382   3886     78 386630    684    131      0]
 [     0    323      2     12    101      6      4   2237     25      0]
 [     0      0      0      1     21      4      0    142    136      0]
 [     0      0      0     26      0      1      0      5      1      5]]


In [36]:
target_names=['Analysis','Backdoor','DoS','Exploits','Fuzzers','Generic','Normal','Recconnaissanse','Shellcode','Worms']
print(classification_report(Y_test_mul_full, y_pred3, target_names=target_names))

                 precision    recall  f1-score   support

       Analysis       0.23      0.03      0.05       455
       Backdoor       0.13      0.82      0.22       394
            DoS       0.56      0.03      0.05      1092
       Exploits       0.73      0.71      0.72      5596
        Fuzzers       0.42      0.70      0.52      4411
        Generic       0.93      0.82      0.87      5038
         Normal       1.00      0.99      0.99    391846
Recconnaissanse       0.51      0.83      0.63      2710
      Shellcode       0.20      0.45      0.28       304
          Worms       0.15      0.13      0.14        38

       accuracy                           0.97    411884
      macro avg       0.48      0.55      0.45    411884
   weighted avg       0.98      0.97      0.98    411884



In [38]:
#FNR=0.77%

In [39]:
roc3 = roc_auc_score(Y_test_mul_full, model3.predict(X_test_mul_selected), average='weighted', multi_class='ovr')
print('ROC AUC score: %f' % roc3)

ROC AUC score: 0.998345
